---
title: "writing notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# notes for Wu thesis
bivalent orientation early metaphase -- search and capture model -- when there are mulitple KT-MT attachmments, (lateral (on the side or not on centromere/KT proper), merotelic MT attachemtn from ooposite poles) and amplitelic (MT from same pole)
then biorientation process starts, --search and capature process (only amplictic Mt-KT attachments get stablize)

Aurora -- detects bad connections, 


_evidence that SAC in oogenesis is leaky_

(Lane et al 2012)

whenn going through the attachment correection, bivalents are thought to be rotated via pulling from MT

Akera 2017 -- chromosomes at different ends of spindle have different densites (in reference to the cortical or central side of spindle (PB or egg))

Wu thesis -- chrm 17 with asymetric centromere str, cenromeres with large major stat drove to (polar body (opposite of drive) (lack of re-orientation, once it ended up on that side))

the biased rotation happened before spindle migratgation (from center of egg to near cortex)

when a aurora inhibitor applied -- the biased rotation of chrm 17 went away and anaphase moved up (by passed SAC as in Lane 2010)

(k-fibre the bundle MTs connected to KT Iwata-otsubo 2017) -- larger KT would provide more k0fiber binding sites

the spindle migration (from center of egg to cortext depends on actin (Li albertini 2013))
cytoplasmic streaming when spindle moves close to the cortex (yi et al 2013)

the KT and centromere seperate when MT's start pulling (trains start moving) (they does seperate whn MT inhibitors are applied)

Coretical KTs undergo greater tension than centrak KTs.  



Review of modifier / popgen models
Indirect forces common assumptions themes across all the modifier models.
Review of cell biology
Look at conserved features of gametogenesis that distinguish male and females
Different Centrosome spindle
Asymmetrical division

aMTOC (Cliff and Schuh 2015, Schuh and ellenburg)
 since there are multiple aMTOC (not 2 centrioles) -- the MTOCs across the sides of the cells could be unven.

after NEBD the aMTOCs are fragmented and coalest into two main clusters (Clift and Schuh 2015 and Luksza 2013). 
(Kolano et al 2012 maintence of spindle)
aMTOC migration to pools is dynamic and self organized.

Wu thesis compared th density of spindles on the central and cortical halves
data suggests that more MTOC are recruited to the cortical side

