---
title: "kableExtraTutorial"
author: "April Peterson"
date: "August 29, 2017"
output: github_document
---


```{r setup, echo=FALSE}
library(knitr)
library(kableExtra)
library(ggplot2)
library(dplyr)

#setwd("C:/Users/alpeterson7/Documents/MLH1repo")
load(file="MLH1_data_setup.RData")

```

This Rmd file displays the boxplots of MLH1 distributions.

```{r, echo=FALSE}
##FIX ORDER HERE
MLH1_data$strain<- factor(MLH1_data$strain,levels =c("G", "LEWES",
                                     "WSB", "PWD","MSM","CAST"), order=T )
#order the data frame
MLH1_data <- with(MLH1_data, MLH1_data[order(sex, strain),])
#set the order of another column, based on another variable (so that when)

MLH1_data <- MLH1_data %>%
  arrange(strain, sex, mouse) %>%
  mutate(file.name = factor(file.name)) #another category that you want the order to match
# sort your dataframe, by the focal categories
MLH1_data$mouse <- factor(MLH1_data$mouse, levels=unique(MLH1_data$mouse))

MLH1_by_F_strain <- MLH1_data[MLH1_data$sex == "female", ]
MLH1_by_M_strain <- MLH1_data[MLH1_data$sex == "male", ]
```

Below is a figure of boxplots all mice from current data batches.

```{r, echo=FALSE}
#save a figure of boxplots for each mouse
bb <- ggplot(MLH1_data, aes(x = mouse, y = nMLH1.foci)) + 
  geom_boxplot(data = MLH1_data, aes(fill = factor(strain), color = factor(sex) ) ) 

bb
```

Below are the boxplots for female MLH1 distributions.

```{r, echo=FALSE}
ff <- ggplot(MLH1_by_F_strain, aes(x = mouse, y = nMLH1.foci)) + geom_boxplot(data = MLH1_by_F_strain, aes(fill = factor(strain) ) )
ff

```

Below are the boxplots for male MLH1 distributions.

```{r, echo=FALSE}
mm <- ggplot(MLH1_by_M_strain, aes(x = mouse, y = nMLH1.foci)) + geom_boxplot(data = MLH1_by_F_strain, aes(fill = factor(strain) ) )
mm
```

Creating Tables with ddply is currently broken Rmd.

```{r}

#q_cutoff_table <- ddply(MLH1_data, .(mouse), summarise,
 #                       total =  length(nMLH1.foci),
  #                      q5 = sum(as.numeric(quality) >= 4, na.rm = TRUE ), 
   #                     q_l3 = sum(as.numeric(as.numeric(quality)) <= 4, na.rm = TRUE)
#)
#q_cutoff_table
```

