---
title: "Discussion"
date: ""
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '5'
    toc_float: yes
  pdf_document: default
  word_document:
    toc: yes
    toc_depth: '5'
bibliography: refs_Main_Report.bib
---


# Differences across models

Explain the model differences; 

## 1.can it be applied to broad scale chromosome level landscape?


-genome wide recombination rates are made of the chromosome level patterns

This is important because general patterns have been observed for the recombination landscape at the chromosome level (also small range of crossovers per chromosome and broad scale pattern (Haenel et al ))


## 2. Does the model account for evolution?

given all the variance observed and fast evolution, models have to have some engine for evolution.

(some source of affecting fitness, or shifting the optima)


# Conserved Sexually Dimorphic Features of Recombination landscape

Conserved heterochiasmy paterns

  - (the canonical pattern has too many exceptions to be the uniform pattern)
    
  - our results have exception, and other exceptions are... 
  
These are the metrics for the _conserved sex differences_




- (heterochiasmy refers to different numbers of chiasmata - and recently has been extended to number of crossovers -- this view / charaecterization is slightly incomplete, since it considers just one cell stage and 1 value (a count))
    
We argue that the sex differences (broaden the definition of heterochiasmy or use a different word) -- which includes more aspects that show conserved sexes differences


Our results indicate, sexes have distinct evolutionary trajectories for genome wide recombinaiotn rate (and landscape) in males nd females).

Conserved features of the landscape may play a role in influencing/keeping the sex specific trajectories. In our examination of the panel of mouse strains, we note several features of the recobmination landscape with conserved sexual dirmophism pattern. 
That is the sex within sex these features show no evolution and consistant pattern of variation.


## male telomeric, female centromeric Typical landscape
<review the typical landscape, one of the major broad scale patterns,
exceptions
consequences, (differences in variation, Sardell paper) >

   1. male telocentric and female uniform landscape / general placement of crossovers.  What is referecened to as typical landscape (Sardell) -- see references sardell kirkpatrick for list of species which show/display this typical phenotype

A difference in the general placement (general recombination landscape), with males having telomere bias and females having more uniform placement of crossovers along chromosomes.

-Exception to landscape (marisupials, birds?)

The Sardel guppies paper was able to deduce (dientangle) that this typical landscape pattern was due to // disentangle the specific components of centromere supression and telomere bias between the male and feamel landscapes. we are not able to do that in these cases (because of inability to estimate the chromosome identity across our sample of single bivalent
s. )


## Chromatin Structure and interference strength

1. SC length  2. connection to interference

general pattern for the sexual dimorphsim the relationship between axis length and CO number
-- axis are longer in females than male, suggesting suport more crossovers (more DSBs)
but the density is less in females.

Our results from MSM and PWD show that the sc length compaction is independant (of the direction of heterochiasmy. Two strains have have more crossovers in males, but females still have longer sc axis. _This indecates that the sexual dimorphism in chromosome organization / DNA compaction is a conserved part of recombination landscape_


The pattern of interference across raw and normalized measures -- also confirms previous results of male having stronger interfere -- due to the longer loops (Petkov)



  2. Explain the connection between interference strength in physical space and (abstracted space)
  
Petkov paper -- states that the sexual dimorphism for interference strength is due to the chromatin structure (meiotic chromosome organization) with the increased interference strength in males being due to longer chromatin loop lengths.

  
  it boils down to, the relationship with axis length and DNA loop size -- 
  
  --females have shorter loops - longer axis and weaker interference

  
  
  Chromatin structure -- the size / length of meiotic chromosomes
  
  same pattern in humans (Gruhn et al 2013)
  
  (exceptions, birds (fish?) plants?) -- examining this is hard due to chromosome size effecs
  
  - This also assumes that the DNA loop sizes have uniform size along and between chromosomes

2. Short axis / longer DNA loops will have stronger interference
This prediction combines the findings of chromatin compaction and interference differences which are intertwined by the transmission of interference along the chromosome axis and the inverse relationship chromatin compaction (axis length and DNA loop sizes).
In physical units (micron) the counting model fits interference well to the 2D linear space of the axis these measures of interference are conserved across sexes in mouse. This is because the counting units are the BASES of DNA loops which is conserved along the 2D length of chromatin axis. When this space is transformed to account for all of the DNA base pairs which are sequestered into the DNA loops above the axis, the strength of interference will vary depending the on underlying chromatin structure. 
The chromatin structure which has longer loops (and shorter axis) will have more DNA bps folded / sequestered into the DNA loops. Thus the strength of interference will be stronger because with each step (count) along the 2D axis, 
more bases pairs are being skipped above the axis. 
  
 
## Greater Within mouse variance in female

- Our results confirm previous findings of females having greater between cell variation (for indiviual females compared to males)
the results -- indicate there is more than can be due to technical noise (for oocytes vs spermatocytes spreads)
also all ovary collections were from early/ young mice -- not due to the maternal age effects, (which has to do with the stability of bivalents at metaphase -- after sexual maturity and ovulation (ref))

We did not observe 

- Because these are inbred strains raised in common / standard lab environment, (an single levels)

_sources of within animal variation_

-age differences

new paper has revealed within nucleus variation for (CO number -- potentially via the chromatin remodeling) (Veller Kleckner)

 Gruhn et al 2013 (the favorite figures)
 
 Gruhn et al 2016 -- not due to the developmental stage of the oocytes (ovulation) (the production line)
 
 
 mouse and humans show greater between cell variance -- this metric isn't really focused on (not many studies that examine inidivial level and both sexes)

3. Within mouse variance differences
In our results we observe more between cell variance in females (across all strains). This pattern has been observed in humans (Lynn et al). (But results of reporting observations of single meiosis in both sexes).

(references, more within animal variance in
(number of crossovers per cell)
but maybe, rec landscapes in general) 

(Gruhn et al), Kong et al?

cattle,

- age effects?

- Hassold hunt



_Relaxed selection_ leads to 


# Evolved Traits

We focused on the largest axis of variation, the faster evolution of genome wide recombination rates in males. One of our primary objectives was to identify other traits which correlate (could explain the increase).

Our results had two notable instances of evolution in the recombination rate (or correlated trait); evolution of precursor number (DSBs) and crossover interference strength. <While SC length and the telomere distances are similar / conserved across the mouse strains>

<We can't distinguish if this is 3 independent instances of evolution in gwRR OR if the patterns are due to shared standing variation, incomplete lineage sorting, but these points are for describing the general patterns.>


# Evolved rates of precursors, DSBs

<define CO:NCO decision, tethered-loop DSB formation SPO11 (cite, paigen? deMassy
setup baier study,  explain >


_the propotion of DSB repaired into crossovers hasn't evolved, the total number of DSBs has evolved_  (following the tethered lop model of DSBs formation -- this would suggest that in the high rec strains, assuming no large difference in the Mb size of the chromosomes, 
during chromatin remodeling in prophase, in the high rec strains the chromosomes have longer axis, allowing a higher number but shorter DNA loops (for SPO11 to make the DSBs).


Our results find evolution between a subset of strains -- demonstrating that the high rec strains have significant higher DSB number.

Our results mirror those found in Baier et al [@baier2014]

Our results show that the ratios of DSB : CO 
**range from X to X which is similar to those presented in [@baier2014] (which report X to X) **

These conserved ratios suggest that the increase in DSB numbers are accompanied by proportional increase in crossovers.

This shifts support away from evolution at the CO:NCO decision to an earlier prophase stage such as when the chromatin compaction is set up. **increase in DSBs is driven by the number of DNA loops** and due to the inverse relationship of loop and chromatin axis length, this would result in longer sc lengths (which reflect the underlying chromatin axis length).

Baier et al found significant differences in sc legnths for 
The tests in our study - show moderate to low significance in the differences in SC lengths. (this is because we have more noise-can't distinguish individual chromosomes)


a study of in house mouse -- using different markers for DSBs and intermediates (markers for the recombination pathway (from DSB to mature crossover))
-different DSB marks, distinct inbred strains two classical lab strains and a wild derived strain from castenus, used FISH for chromosome specific measures

our results are similar in several ways
- correlation of final MLH1 and DBS counts, SC measues correlate with the DSB number (even tho the differnces we observe in our study are -- slight / less significant -- we attribute that to chromosome specific noise )


Evolution of recombination rates via the number of precursors -- (has been proposed -- ) (Bairer et al). 



# INTERFERENCE evolution

1. Review results
-The rapid evolution of the genome wide rate in our high rec strains is due to more enrichment of 2CO which have distinct rec landscape from the 2COs in low rec strains.

These results were unexcepted and differ ffrom the major patterns listed in the literature (otto payseur, argawal Korol. (it also goes against the logical assumptions models of fitting more crossovers along the SC chromosome axis space)


Yet (we are confident that this pattern is not due to errors).

 the IFD distributions show less variance in the high rec strains, which would have MORE Chromosomes (Chm1 to Chm7) compared to the low rec strains which have fewer 2Cos (presumably limited to large chromosomes).


-Also:
	-These results are different from the sex differences because the difference is seen in both the raw and normalized IFD, indicateing the mechanism  / physcial strength (interference strength (signal) mediated through the SC has evolved.
	
	-The difference in interference patterns is driven by the difference in the rates of small IFD observations, (mean vs median). a pattern that is suggestive of selection agisnt short IFDs


There is a model that predicts this positive ocrrelation. The goldstein results (reviewed in ottoPayseur). when the number of crossovers (the obligate crossover assumption is more strict / the
breifly, the model simulates / sets up a scnario where a modifer acts through the probabilty of flanking regions having 0 or 2 crossovers. ith crossover assuance, recombination rate increases the further apart the loci are spaced (?)


Additionally there are a handful of empircal results which also show the unexpected pssotive correlation between gwRR and interference strength.

1. Cattle (Ma?), when comparisons of genetic map length and interference strength are made across strengths within sex, the strain with the higher genome wide recombinaiton rate also has stronger interference (measured as nu gamma parameter)

2. The IFDs from (Beth's cross) a related house mouse cross show that the PWD (same strain, different mice) had longer IFD compared to Cast (HVR unpublished data). (also gamma?)

3. In Peromyscus, the wild mice had higher gwRR and stronger (gamma nu estimates) compared to lab raised mice of the same speicies [@Peterson]

<note about the differences in the patterns>  assumptions with gamma dstribution and linkage maps, (closer to infinte genetic space), less weight on crossover assurance - more weigth on 
(pooled SC/chromosome length gives strong correlation )


<which is much different than when a single chromosome is examined (by itself), finite 2D length, crossover assurance, weaker correlation with ((the closer to chromosome level for SC legnth metric / summary, the weaker the correlation with crossover number))





2.  Review the assumptions for measuring CO interference in different ways.
The logical model: Crossover interference is a mechanism of suppressing crossovers, negative relationship between interference strength and gwRR. More crossovers can fit along the chromosomes and results in more crossovers overall.
Examples of empirical results supporting this pattern;  Otto Payseur, (Ruiz-Herrera? Bomblies?)
Quantifing using the gamma distribution: 
Caveats,  This doesn't make since for the general recombination landscape:   i) finite chromosome length and ii) limited range of crossovers per chromosomes (1 to 4).
Alternative interference characterization:  i) the number of crossovers are held constant and ii) transform / generalize the rec landscape, (focus on how the rec landscape would change instead of the genome wide rate) iii) assume crossover assurance.
	-The Goldstein model, models predicts a positive correlation with interference strength and higher recombination rate. A modifier which changes the probability of the recombination landscape having 0 crossovers to 2 crossovers, (driven by crossover assurance).

-Examples of empirical results which show this result / pattern
	-(cattle) comparison WITHIN sexes
	- Preliminary results for F2 cross (Hannah's work), (PWD vs CAST)
	(maybe more once I start looking closer)

4. HYPER-Crossover experiments. (review the effects when crossover number is artificially altered)



# Explanations and Model testing  


This section refers to the matrix of models and results from this study where we (conceptually test if each model would support our results). We were motivated to run a comparison of 


## 1.Gamete selection

The process where gametes are competing - so there is stronger selection for 1 form of gamete vs the other (stronger directional selection) (the gamete with more competition / the sex with more variance in reproductive fitness will have lower overall recombination rate.

<go through the squares>

this is a modifer model it abstracts the genome area.

This model predicts the evolution of heterchiasmy -- through models (that build on selection to reduce recombiantion for the sex with geater varatince in fitness effect)

this model doesn't predict that the heterochismy direction would reverse.



## 2. SACE

Extension of reduction principle. Results in large blocks of genetic areas being kept together in male meiosis.

-- this model is an extension of the modifer model presented in Lenormand


-- (basics)
 extends the lenomand focusing on two conditions. first that the stength of epistatsis in dependant on the cis or trans nature. the authors note that this would apply to gene archtechture (and increase with in cis ) -- where the regulatroy region and coding region of a gene evolve (together)
 
 second that the relative interference strengths differnt between male and female.  This can apply to (genes acting in sexual antagonism) or can be mediated via imprinted genes.
 
This new model has **strengths**

  - It matches fine scale differences in how DSB hotspots had different sex specific strengths with varied due to sex, epigenetc landscape and the gene architecture (Brick et al)

 - incorporates know cellular / molecular mechanisms with a very common pattern sexual dimorphic recombination rate landscape.
 
- extends modifer model to explain a chromosome based / level pattern
 

_weaknesses_, and ways the model diverges from our results

 - the simulation present in the paper are too weak to support the rapid spread of such a modifer system (selection coefficients are too weak to support the evolution -- spread of such a modifer.)
 
- Other ways this model departs from our results, 

-Always predicting male will be lower recombination rates (or risk breaking up the epistatsis blocks) -- which doesn't fit with our results of faster male specific evolution in gwRR.

However / while not explicitaly arameterized or predicted in this model,
 -- this model predicts larger chuncks of chromosomes will segregate together
 (as outlined in Veller et al)
 
 our results of stronger male interference and stronger interference in high rec strains have the same consequences as predited from this modle 
 

## 3.Two-locus (protect for drivers)

Asymmetric division of egg opens them up to meiotic drivers. Recombination modifiers for sex specific female landscape will decrease the chances of driving centromeres to segregate to the egg by increasing the number of crossovers and placing them across a larger area of the genome (uniform placement).

**model basics**

'break up driv system consiracies'

**strengths**

a clear fitness effect (the drive)

explains female landscape pattern in reference to the centromere (presummed location of drivers), yet the model doesn't scale down to chromsome level (such as to explain, chromosome size differences)

**weaknesses**

(modifers - driver systems everywhere!), impossible to verify, doesn't account for male landscape pattern (supression from centromere to end)


## 4. Segregation and physiological Spindle Differences


### The CONTEXT of MEIOSIS

the study confirmed preivously identified sexual dimorhisc patterns in regard to the recombiantion landscape (in mammals) -- in the goal of unifying all of these results, we sough to investigate physiologycal aspects of gametogenesis which have conserved sexual dimorphic features.

LOOK at the oogenesis and spermatogenesis as the context for meiosis (and how )

lead us to ask, how the different contexts of meiosis could influence recombination rates (the recombinaiton landscape)

(not sex chromosome)

while there are many different forms, flavors of anisogamy (cite that one paper)

symetrical vs asymetrical gamete division


A fundamental difference in meiosis (MI) for males and females is the presence of the centrosome which serves as a nucleation site for MT at each pole (and changes the shape of the spindle). (Our hypothesis is that the tension in a centrosome spindle is stronger (or more uniform) since all MT-KT are anchored at single points across cells (the two centrosomes). This will also make prediction for the spindle assembly checkpoint (SAC), which is stronger/stricter in smaller gametes with centrosomes.  (the SAC is more sensitive to achiasmate bivalents on the spindle / better at detecting a lack of tension).
Whereas in the acentrosome spindle is more diffuse (across a larger area) and the tension across bivalents are anchored by multiple MTOCs, resulting in weaker tension force or less uniform strengths across all the bivalents within the cells. The SAC in eggs seems to be weaker/leakier, that is more achiasmate bivalents are required to trigger the SAC (stop the division).


_main sex differences in spindle_ are the anchoring of MT at opposite poles

in males there are centromsomes for Mi and MII divisions
where are in oocytes, a (universal) conserved feature of oogenesis in many species is that they loose centrosomes -- instead the MTs are anchored at mulitple aMTOCs.

There is potential for these aMTOC to be unevenly distributd across the cortical and central side of the spindles (Wu et al, Schuh and ellenberg) --- (could be an origin of different tension / pulling )

The survalence of SAC in oocytes might be decreased due to large volumne difusing the signals.



### CO placement translates to bivalent shape


**still an open question of if and how the CO number and placement of crossovers translates to different fitness values for segregation rates**

the metric / amout of sister cohesion might be an good place to start


the ultimate goal is proper disjunction of chromosomes, the main checkpoint is spindle assembly checkpoint (SAC) which responds to the tension signal across chiasmata


we like this model because it can be applied to **both our results** for i) sexual dimorphism variation and ii) the fast male evolution in gwRR and recombination landscape.

Uses / centers around one of the best known selection factors on meiotic division, anneuploidy. Several other facors related to meiotic recombiniation center on **segregation** (obligate chiasmata, lower bound of the genome wide rate) it's not unbelievable that the recombination 


for the distinct **evolutionary patterns** selection on the recombination landscape via the spindle (segregation checkpoint), 



_leaky SAC_ for oocytes (is known) .. meaning that bivalents / homologs without proper tension force


(potentially this bad checkpoint is adaptive for thwarting centromere drive systems, which work through the SAC and tension signals)





how the SAC spindle works, correctly

evidence that the oocyte spindle is leaky

_precition that the leaky spindle makes relaxes selection_

aTMOC's  (because there are mulitple, these could be uneven across the cell)


_asymetrical division_

this makes egg weak to driving centromeres which (are segregation distortors), that means some centromeres segreation (rotate to the polar body side of the egg)



_number of placement of crossovers influencing spindle_

For this model we propose that the number and placement of crossovers -- will affect the 





_strengths of model_


_weakness_ 

No very few spermatocyte spindle data  (it's assumed to )




_review the correct SAC_


References:
Schuh Ellenberg 2007 spindle 


#### notes for Wu thesis
bivalent orientation early metaphase -- search and capture model -- when there are mulitple KT-MT attachmments, (lateral (on the side or not on centromere/KT proper), merotelic MT attachemtn from ooposite poles) and amplitelic (MT from same pole)
then biorientation process starts, --search and capature process (only amplictic Mt-KT attachments get stablize)

Aurora -- detects bad connections, 


_evidence that SAC in oogenesis is leaky_

(Lane et al 2012)

whenn going through the attachment correection, bivalents are thought to be rotated via pulling from MT

Akera 2017 -- chromosomes at different ends of spindle have different densites (in reference to the cortical or central side of spindle (PB or egg))

Wu thesis -- chrm 17 with asymetric centromere str, cenromeres with large major stat drove to (polar body (opposite of drive) (lack of re-orientation, once it ended up on that side))

the biased rotation happened before spindle migratgation (from center of egg to near cortex)

when a aurora inhibitor applied -- the biased rotation of chrm 17 went away and anaphase moved up (by passed SAC as in Lane 2010)

(k-fibre the bundle MTs connected to KT Iwata-otsubo 2017) -- larger KT would provide more k0fiber binding sites

the spindle migration (from center of egg to cortext depends on actin (Li albertini 2013))
cytoplasmic streaming when spindle moves close to the cortex (yi et al 2013)

the KT and centromere seperate when MT's start pulling (trains start moving) (they does seperate whn MT inhibitors are applied)

Coretical KTs undergo greater tension than centrak KTs.  



Review of modifier / popgen models
Indirect forces common assumptions themes across all the modifier models.
Review of cell biology
Look at conserved features of gametogenesis that distinguish male and females
Different Centrosome spindle
Asymmetrical division

aMTOC (Cliff and Schuh 2015, Schuh and ellenburg)
 since there are multiple aMTOC (not 2 centrioles) -- the MTOCs across the sides of the cells could be unven.

after NEBD the aMTOCs are fragmented and coalest into two main clusters (Clift and Schuh 2015 and Luksza 2013). 
(Kolano et al 2012 maintence of spindle)
aMTOC migration to pools is dynamic and self organized.

Wu thesis compared th density of spindles on the central and cortical halves
data suggests that more MTOC are recruited to the cortical side


5. Model prediction
The models above which predict directional selection on the recombination landscape in males: SACE and Spindle differences are most parsimonious for the models review in this paper. The reduction principle wouldn't predict males diverge in genome wide rates and two locus modifier doesn't predict males gwRR would be higher than females.

Consequences of evolution in the number and placement of crossovers / evolution of interference strength:
Spindle / SAC model: The number and placement of crossovers changes the resulting amount of sister cohesin involved the tension signal, which affects the tetrad/chiasmata structure at MI when the homologs are pulled apart (Hollis et al 2020, Lee et al 2019).  This model predicts a difference in the meiotic spindles or division mechanism between high and low rec strains. 
ii. SACE: For the 2CO in the high rec males, larger blocks of chromosomes are kept together in the next generation.
	This model would predict greater reproductive variance for males.


# Future Steps


be aware of sex-specific and sex average biases

- linkage / R between two foci is sex averaged

- Celegans -- cytlogy focuses on oogenesis  and genetic maps are often from hermaphrodites (selfing -- sperm and egg landscapes are merged in hemaphordites)


-- the value of Chromosome level measures -- incorporate chromosome behavior into models

-  more attention to cell physiology and biophysics (conserved nature of meiosis pathway (and mitosis ) -- use some models such as Sc for manipulation) (Murkarjee gardner -- quantify the spindle tension

-- lack of SC length prophase cell charaecterization
-- comparisons within and between sexes (that cattle paper)

# Reference