---
title: "Intro Outline"
author: "April Peterson"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: '5'
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
bibliography: refs_Main_Report.bib
---

### **0.   Importance of recombination rate**

(1) Meiosis can be reduced to the expression of (2n -> 4n -> 2n -> 1n) which tracks the duplication of a diploid genome into haploid cell products. The meiotic program relies on crossovers and the process of recombination to ensure the correct separation of chromosomes. The total number of COs per cell (at the 4n stage) is equal to the genome wide recombination rate (gwRR). The gwRR regulates populations responses to selection, and determine the fate of novel mutations by transfering beneficial mutations onto novel genetic backgrounds or by breaking linkage of bad mutations from benefical backgrounds.

This process shapes the genomic patterns of genetic variation, with high recombination areas of genome having more nucleotide variation while areas of low recombination have decreased genetic variation (Begun Aquadro, Nachmann, Payseur).


(mention fitness more explicitly). The lower bound/threshold is thought to be an obligate crossover per homolog pair -- is a checkpoint for proper chromosome segregation (Hunt Nagaoka, Hassold). While too much recombination (ectopoic recombination) and DNA damage preceeding crossover formation (may be a constraint for an upper threshold. (cite other than Inoue, OttoPaysuer?).  **As the gwRR influences the evolution of other traits, it is important to document and understand the evolutionary patterns for the genome wide recombination rate itself.**



# **1. Understanding levels of variation in gwRR**

1a. There is substantial in gwRR variation within species (across populations) and (across individuals)
•	While there are fewer measures from closely related species, variation at this level is more restricted to finer scales (hotspot level / recombination landscape level).

1b. Sex is one of the most notable axes along which individuals vary 

•	Long history since the discovery -- in fruit flies and silk moths
Heterochiasmy was first documented --- 



(2) One forms of sexual reproduction, anisogamy where a species has distinct gametes, there is no first principle which would predict the evolution of sexually dimorphic recombination rates. Yet sexual dimorphism for the gwRR, called heterochiasmy, is commonly observed, suggesting that other meiotic traits which distinguish the gametes may impose selection for sexually dimorphic recombination rates. 


As detailed in Sardell Kirkpatrick, (for a species with hetreochiasmy, rarely do they have a single recombination landscape. Instead there are broad scale differences recombination rate along 


•	Most species have more recombination in females than males, 


•	Crossover placement is sexually dimorphic: male telomeric, female uniform placement


•	SC length / meiotic chromosome length is longer in females of a few mammal species, but there are exceptions, Celegean (not much different) and A.thalnia (opposite direction) (Cahoon and Libdua).

The cellular process of meiosis can be reduced to the expression of (2n -> 4n -> 2n -> 1n) which tracks the duplication of a diploid genome into haploid cell products. The meiotic program relies on crossovers and the process of recombination to ensure the correct separation of chromosomes. **Under one of the most common forms of sexual reproduction, anisogamy where a species has distinct gametes, there is no first principle which would predict the evolution of sexually dimorphic recombination rates.** Yet sexual dimorphism for this trait, called heterochiasmy, is commonly observed in dioecious species, suggesting that other meiotic traits which distinguish the gametes, for example symmetrical vs asymmetrical cell division, may impose selection for sexually dimorphic recombination rates. 


As reviewed in Cahoon Libuda, there are fundamental differences for the two forms of gametogenesis: length of timing (spermatogenetsis faster), sensativeity to errors, asymetrical cell division vs symetrical cell devision.   The physiological consequences of these cell volumne may have an impact meiotic machenery. 

the authors track the sexual dimorphism patterns in the recombination landscape for three species.


1c. There are still gaps missing from the field
•	An understanding of how sex shapes the evolution of recombination cannot be achieved with available data. Comprehensive comparisons of female and male recombination rates usually come from outbred populations (human, dog, cattle, sheep, mouse collaborative cross REFS), in which the role of sex is confounded with the contributions of genetic variation. Although it is clear that the relationship between female and male recombination rates can differ among species, comparisons between and within closely related species are missing. 
•	Direct contrasts between females and males across a common, diverse set of genomic backgrounds would reveal whether the recombination rate evolves differently in the sexes.


# **2.  The House Mouse is a great model for uncovering evolutionary patterns at a short timescale.**
•	House mouse complex comes from a recent radiation providing an opportunity to interrogate variation at short evolutionary scales.
•	Wild derived inbred strains generate the best comparison of females and males, besides the sex chromosomes, the mouse for each genome is highly similar.
•	Unlike some house mouse strains, all strains have the same karyotypes, 20 pairs of acrocentric chromosomes.
•	Classical lab strains of mice have generated a mountain of knowledge regarding the genetics and molecular pathway of meiosis.
•	House mouse is suited for single cell cytology approaches.



# **3. What we accomplished in this paper**
•	We report a rare, direct, evolutionary comparison of recombination rate in females and males (or something like this).
•	We quantify gwRR of both sexes, from 3 subspecies and outgroups.
•	We use rare strains with a recent origin from multiple geographic locations of the species territory.
•	We quantified meiotic chromosome morphology (SC length) and placement of crossovers to comprise an approximate picture of the recombination landscape.
•	Our results indicate rapid male specific evolution of gwRR.


(Lenormand, BurtBellOther, Shapley,)
HetC theories:   (Brandavain, Trivers ??? Lenormand, Sardell-Kirkpatrick, (hulten? Handel?)

wild pops genetic diversity and within species measures

my pero refs, honey bee RR, ritz noor


# text

  Meiosis can be reduced to the expression of (2n -> 4n -> 2n -> 1n) which tracks the duplication of a diploid genome into haploid cell products. The meiotic program relies on crossovers and the process of recombination to ensure the correct separation of chromosomes. Under one of the most common forms of sexual reproduction, anisogamy where a species has distinct gametes, there is no first principle which would predict the evolution of sexually dimorphic recombination rates. Yet sexual dimorphism for this trait, called heterochiasmy, is commonly observed in dioecious species, suggesting that other meiotic traits which distinguish the gametes, for example symmetrical vs asymmetrical cell division, may impose selection for sexually dimorphic recombination rates. 

