---
title: "Material Methods"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: '5'
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
bibliography: refs_MatMeth.bib
---


```{r set.up, echo=FALSE}
#set wd
#load datafile

#common bugs
#html won't compile -- one of my citations in bib was breaking things
```


# Mouse Husbandry


To access natural genetic variation for *Mus musculus*, wild derived inbred strains were used. The Mus musculus PWD/PhJ, PERC/Eij, WSB/EiJ, LEWE/EiJ, MSM/MsJ, MOLF/EiJ, CAST/EiJ, CZECHII/EiJ were purchased from Jackson labs (Maine, USA). The strains of KAZ/TUA, TOM/TUA, AST/TUA, and HMI/TUA were cryo-derived from Biological Resource Center (BRC) at Riken (Ibaraki, Japan).  (https://en.brc.riken.jp).
The related species of *Mus caroli* CAROLI/EiJ and *Mus spretus* SPRET/EiJ were purchased from Jax labs (https://www.jax.org) and *Mus spicilegus* SPIC/Eij from Riken. 

 All mice were housed UW-Madison Biotech and MSC facilities - following the protocols.  A breeding colony of wild derived 
*Mus musculus* mice sampled from Gough Island (GI)is maintained at UW Veterinary school facilities.
 Mice were feed on dry standard breeder chow. Some strains sunflower seeds, nestlets and larger cages were added to improve fertility and litter survival. Adult mice were euthanized by CO asphyxiation. Neonate and embryonic mice were euthanized by decapitation following the protocols approved by the Institutional Animal Care and Use Committee at the University of Wisconsin-Madison.

Over the course of data collection some breeding colonies  mice were moved from facilities. Additionally the GI strain was kept at a separate facility.  (evidence for environmental (room) effect on (MLH1 / SC lengths / a variety of meiotic traits was tested for. We observed no effect, Supplemental figure))



# Tissue Collection and Immunohistochemistry

Spermatocyte spreads were collected and perpared as described in [@peterson_2019] . The majority of mice used were between 5 and 12 weeks, (supplemental table). However some strains had problems breeding, so testes from older mice were collected. We found a (small/no) age effect on MLH1 counts for male mice (Supplemental Figure)). 

The only difference between preparation of spermatocyte and oocyte spreads was the volumns of the hypotonic buffer was 300 u l instead of 3ml.

The vast majority of oocyte data was collected from neonate litters/mice between 5 to 48 hours. This approach maintain breeding pairing and still result in prophase oocytes (cite timeline of oocytes in neonates). (differences were assessed between embryo samples and neonates?). Precise staging of embryos by checking copulary plugs was difficult/not feasible in many of these wild derived strains due to their behavior. Embryonic samples were collected when pregnancy noted in females, embryos were staged based on (X table markers).


Meiocyte spreads were made following [@peters_1997]. For testes the tunica was removed and whole testes was incubated in 3ml of hypotonic solution for 45min. For ovaries after dissection, the pair of ovaries were decapsulated in cold PBS and both were incubated in 300ul of hypotonic solution for 45 min.

After incubation, gonads were transferred to sucrose solution -for mastication to make a cell slurry which was transferred to 80ul of 2% PFA solution. Cells were fixed in this solution and dried in a humid chamber at room temperature overnight. The next morning, slides were treated with a photoflow (Kodak, cite) wash.


Staining / Immunohistochemistry

The same staining protocol was applied to spermatocyte and oocyte spreads.
The staining protocol was based on X with some adaptations, and same as previously described in Peterson et al 2019.

Explain list recipes for DMC1 since these haven't been listed before


# Image Processing

Images of cells were capture using a Zeiss Axioplan 2 microscope with AxioLab camera and Axio Vision software (Zeiss, Cambridge, UK). 

Preprocessing, including cropping, noise reduction, and histogram adjustments, was performed using Photoshop (v13.0).

For MLH1 pachytene characterization, Cells with a full karyotype (19 acrocentric bivalents and XY for spermatocytes or 20 acrocentric bivalents for oocytes), distinct foci, and intact bivalents were included for quantification.
Reprocessing in Photoshop (cite). Image file names were anonymized before manual scoring of MLH1 or DMC1 foci.

Repeatability was assessed by X (comparing mulitple counted images)

Measures of meiotic chromosomes generated by using ImageJ/Fiji (v1.52) [@fiji].

total Sc was measured [@wang_2019_sc]

Bivalent level measure were done [@peterson_2019]



# Statisical Analysis

0. discribe basic assesment and comparison of MLH1 means (and how it is proxy for genome wide recombination rates)
- assessment and treatment of data quality control ect (correlation measured X)

The distributions of CO counts per cell was assessed for normailty (supplemental figure). Mouse mean MLH1 count was used to get around the bad discreet nature of count data. (normality was confirmed with X distribution, supplemental figure). <re-write this dumb paragraph>

<<<<<<< HEAD:doc/MatMeth.Rmd
We choose to use a **mixed model framework** to interpert the patterns of variation. For interperting patterns of mean MLH1 count within and between house mouse subspecies. 

1. write equation

=======
Statistical analysis was performed in R (v3.5.2)[@Rstudio]. mixed models use lmer4 package (cite)

1. framework for analyzing the MLH1 evolutionary patterns across mus species complex. (what is the main question we were tackling when designing this framework?)

2. write equation, discribe terms (proxies for within and between polymorphsm)
logic / choices for fixed and random effects

3. what are the 2 general / basic questions this framework can be applied to.

$X \sim mouse average MLH1 ~ sex + subspecies + random(strain) + \xi $
< can't get the equation in the right format. I think this breaks the pdf kniting.>

4. how can DMC1 measures be added to the mixed model

5. discriptions of mlh1 outside of framework (missing female data)


In this model
mixed model, observations of mouse means of mlh1, all data with both male and female observations

The main effects and the interaction of subspecies and sex were coded as fixed.

Subspecies, sex and subsp*sex are fixed effects

Strain was coded as a random effect, since in this experimental design we consider it as a sample of natural genetic variation for each subspecies. We also included a term to allow for strains to have a specific sex effect.


This model allows us to estimate and test the fixed effects (sex and subsp), and variation in mean MLH1 counts due to strain effect.

We use the subspecies term as a way to quantify between group variation (or divergence) and the random strain effect to quantify within group variation (or polymorphism). (in a sex specific manner)


From the mixed model the estimates of heterochiasmy (sexual dimorphism) are a combination of subspecies and strain specific sex effects.

We can also compare the size of the sex effects between (subspecies) and within (strain) mouse groups. (ie is the male or female strain effect larger? is there more variance due to random strain effect in male or females?)

I may have to do more research/reading on testing the random effects.
-specific statistical tests; (means, non-parametric kurts wallis t-test?) (correlation coefficient (function))
linear models lm() from X package.

-specific R packages
-non-parametric  (tests and measures for dealing with count data)
-hypothesis tested (size, DSB number)
=======


Comparison/analysis of variation in MLH1 counts within and between groups was done within a general linear/ mix model frame work, using X package (cite).
(we used this frame work as proxy for 'polymorphism' and 'divergence' in MLH1 counts across house mouse and closely related species.)


# References
