---
title: "MLH1 Current Data Report"
author: "April Peterson"
date: "June 3, 2019"
output:
  pdf_document: default
---

```{r setup, echo=FALSE, include=FALSE}
#require("knitr")
#knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(dplyr) #this is a newer version of plyr
library(ggplot2)
#set dir
setwd("~./MLH1repo/")
#load data
load(file = "data/MLH1/MLH1_data_setup.RData")
source("src/CommonFunc_MLH1repo.R")
```




## Strain Level Plots


```{r strain.table, echo=FALSE}

AP_strain_table <- ddply(MLH1_data, c("strain", "sex"), summarise,
                         Nmice = length(unique(mouse)),
                         Ncells  = length(adj_nMLH1.foci),
                         mean_co = format(round(  mean(adj_nMLH1.foci), 3 ), nsmall=3),
                         var = format(round(   var(nMLH1.foci),3), nsmall=3),
                         sd   = round(sd(adj_nMLH1.foci), 3),
                         se   = round(sd / sqrt(Ncells), 3),
                         cV = round( (as.numeric(sd) / as.numeric(mean_co) ),3)
)



AP_strain_table <- add_subsp(AP_strain_table)
#("black", "#56B4E9","cadetblue4","cadetblue","coral1","#E69F00", "yellowgreen") )

#set the order for a factor
AP_strain_table$subsp<- factor(AP_strain_table$subsp,levels =c("Dom", "Musc",
                 "Cast","Spretus", "Spic", "Caroli", "other"), order=T )

AP_strain_table$strain<- factor(AP_strain_table$strain,levels =c("G", "LEW",
                        "WSB", "PWD","MSM","KAZ","CAST","HMI","SPIC","SPRET"), order=T )

#puts table in the right order
AP_strain_table <- AP_strain_table %>%
  arrange(strain, sex, subsp) %>%               # sort your dataframe, by the focal categories
  mutate(image.title = factor(strain)) #another category that you want the order to match

colnames(AP_strain_table) <- c("strain","sex","Nmice","Ncells","mean_co","var","sd","se",
                          "cV","subsp","extra")

AP_strain_table$mean_co <- as.numeric(AP_strain_table$mean_co)

MLH1_by_F_strain <- AP_strain_table[AP_strain_table$sex == "female", ]
MLH1_by_M_strain <- AP_strain_table[AP_strain_table$sex == "male", ]


#MLH1_by_F_strain <- MLH1_by_F_strain[-c(7),]

#re-adjust the mouse table
AP_mouse_table$subsp<- factor(AP_mouse_table$subsp,levels =c("Dom", "Musc",
                                                               "Cast","Spretus", "Spic", "Caroli", "other"), order=T )

AP_mouse_table$strain<- factor(AP_mouse_table$strain,levels =c("G", "LEW","WSB",
                                                               "PWD","MSM","KAZ","CAST","HMI","SPIC","SPRET"), order=T )


AP_mouse_table <- AP_mouse_table[AP_mouse_table$mouse != "11jan18_WxL.F1_m1",]


```


```{r strain.level.female, echo=FALSE}

man_x_fspace <- c(.35, .5, .75,
         2.2, 2.5, 2.8,
          3.6, 4, 4.5)

ff_plot <- ggplot(MLH1_by_F_strain, aes(y = as.numeric(mean_co), x=man_x_fspace, color=strain))+
  geom_point(size = 4) +
  scale_y_continuous(breaks = seq(20,32, by=2)) +
  coord_cartesian(ylim = c(20,32))+
  xlim(0,5)+
  geom_errorbar(aes(ymin = as.numeric(mean_co)-(as.numeric(se)*2), 
                   ymax = as.numeric(mean_co)+ (as.numeric(se)*2)),size=1.2, width=0.1) +
  
  scale_color_manual(values=c("#56B4E9","cadetblue4","cadetblue","coral1","#E69F00", 
                              "red", "green","black", "grey"))+
  
   labs(x="", y= "Female MLH1 Foci") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line.y = element_line(colour = "black", size = 1.5), #legend.position="none",
        axis.ticks.y = element_line(colour = "black", size = 1.5),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), size=20),
        
        axis.text.y = element_text(size=15, face="bold"),
      axis.title.x=element_blank(), axis.line.x = element_blank(), axis.text.x=element_blank(), axis.ticks.x = element_blank() ) +
   
   annotate("text", x = c(mean(man_x_fspace[1:3]), mean(man_x_fspace[1:3]), 
    mean(man_x_fspace[4:6]), mean(man_x_fspace[4:6]), 
    mean(man_x_fspace[7:9]), mean(man_x_fspace[7:9])),
          y = c(21, 20.5, 21, 20.5, 21, 20.5) ,
    label = c("M.m.","domesticus","M.m.","musculus","out","groups"),fontface = 'bold.italic', hjust = 0.5, size=5) +
  ggtitle("Female MLH1 Counts \n -/+ 2 SE")
  
  #annotate("segment", x= mean(man_x_fspace[1:3])-.3, xend=mean(man_x_fspace[1:3])+.3, y=21.5, yend=21.5, colour="black",size=1.5) +
   # annotate("segment", x=mean(man_x_fspace[4:6])-.3,xend=mean(man_x_fspace[4:6])+.3, y=21.5, yend=21.5, colour="black", size=1.5) +
 # annotate("segment", x=mean(man_x_fspace[7:9])-.3, xend=mean(man_x_fspace[7:9])+.3, y=21.5, yend=21.5, colour="black", size=1.5)


```


```{r strain.level.male, echo=FALSE, include=FALSE}

man_x_mspace <- c(.35, .5, .75, 
            1.5,2,2.3,
            3.1,3.4,
            4.5,4.8, 5)

mm_plot <- ggplot(MLH1_by_M_strain, aes(y = as.numeric(mean_co), x=man_x_mspace, color=strain))+ 
  geom_point(size = 4)+ 
#  ylim(18,32) +  
#  scale_y_continuous(breaks = seq(18, 34, by = 2)) +
  scale_y_continuous(breaks = seq(20,35, by=2)) +
  coord_cartesian(ylim = c(20,32))+
  xlim(0,5)+
  geom_errorbar(aes(ymin = as.numeric(mean_co)-(as.numeric(se)*2), 
                    ymax = as.numeric(mean_co)+ (as.numeric(se)*2)),
                size=1.2, width=0.1)+
  
   #geom_errorbar(aes(ymin = as.numeric(mean_co) - as.numeric(se), 
  #                  ymax = as.numeric(mean_co)+ as.numeric(se),
   #   size=.5, width=.1))+
  scale_color_manual(values=c("#56B4E9","cadetblue4","cadetblue",
                "coral1","#E69F00","red", "yellowgreen","green", "purple", "black") )+ #"olivedrab2", (HMI) ,"orchid" (SPRET)
  labs(x="", y= "Male MLH1 Foci") +
  
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line.y = element_line(colour = "black", size = 1.5), #legend.position="none",
        axis.ticks.y = element_line(colour = "black", size = 1.5),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), size=20),
        axis.text.y = element_text(size=15, face="bold"),
  axis.title.x=element_blank(), axis.line.x = element_blank(), axis.text.x=element_blank(), axis.ticks.x = element_blank()) +
   
  annotate("text", x = c(mean(man_x_mspace[1:3]), mean(man_x_mspace[1:3]), 
                         mean(man_x_mspace[4:6]), mean(man_x_mspace[4:6]),
                         mean(man_x_mspace[7:8]), mean(man_x_mspace[7:8]),
                          mean(man_x_mspace[9:10]), mean(man_x_mspace[9:10])),
           y = c(21,20.5, 21,20.5,21,20.5,21,20.5 ),  size=5,
    label = c("M.m.","domesticus","M.m.","musculus","M.m.","castaneus", "out", "groups"),hjust = 0.5, fontface='bold.italic') +
 
   annotate("segment", x= mean(man_x_mspace[1:3])-.3, xend=mean(man_x_mspace[1:3])+.3, y=21.5, yend=21.5, colour="black",
           size=1) +
  annotate("segment", x=mean(man_x_mspace[4:6])-.3,xend=mean(man_x_mspace[4:6])+.3, y=21.5, yend=21.5, colour="black",
           size=1) +
  annotate("segment", x=mean(man_x_mspace[7:8])-.3, xend=mean(man_x_mspace[7:8])+.3, y=21.5, yend=21.5, colour="black",
           size=1)+
  annotate("segment", x=mean(man_x_mspace[9:10])-.3, xend=mean(man_x_mspace[9:10])+.3, y=21.5, yend=21.5, colour="black",
         size=1)

```


```{r call.plots}

ff_plot

mm_plot
```



## Mouse Level Plots

plots by categories. (which have longer SCs?)

```{r mouse.level.female, echo=FALSE}

female.mice <- AP_mouse_table[AP_mouse_table$sex == "female",]

female.mice <- female.mice %>%
  arrange(strain,subsp) %>%         # sort your dataframe, by the focal categories
  mutate(image.title = factor(strain)) #another category that you want the order to match

# sort your dataframe, by the focal categories
female.mice$mouse <- factor(female.mice$mouse, levels=unique(female.mice$mouse))


female_mouse_plot <- ggplot(female.mice, aes(y =mean_co, x=mouse, color=strain))+geom_point()+
  scale_color_manual(values=c("#56B4E9","cadetblue4","cadetblue","coral1","#E69F00", 
                                                  "red", "green", "black", "grey"))+
  labs(x="", y= "Female MLH1 Foci")+ ggtitle("Female mouse MLH1 counts")+

  geom_errorbar(aes(ymin = as.numeric(mean_co)-(as.numeric(se)*2), 
                    ymax = as.numeric(mean_co)+ (as.numeric(se)*2)),
                size=1, width=0.05)+
  theme(axis.title.x=element_blank(), axis.line.x = element_blank(), axis.text.x=element_blank(), axis.ticks.x = element_blank())

```



```{r mouse.level.male, echo=FALSE}

male.mice <- AP_mouse_table[AP_mouse_table$sex == "male",]

male.mice <- male.mice %>%
  arrange(strain,subsp) %>%         # sort your dataframe, by the focal categories
  mutate(image.title = factor(strain)) #another category that you want the order to match

# sort your dataframe, by the focal categories
male.mice$mouse <- factor(male.mice$mouse, levels=unique(male.mice$mouse))

male_mouse_plot <- ggplot(male.mice, aes(y =mean_co, x=mouse, color=strain))+geom_point()+
  scale_color_manual(values=c("#56B4E9","cadetblue4","cadetblue","coral1","#E69F00", 
                              "red", "green", "black", "grey", "grey3"))+
  labs(x="", y= "Male MLH1 Foci")+ ggtitle("Male mouse MLH1 counts")+
    geom_errorbar(aes(ymin = as.numeric(mean_co)-(as.numeric(se)*2), 
                  ymax = as.numeric(mean_co)+ (as.numeric(se)*2)),
              size=1, width=0.05)+
  theme(axis.title.x=element_blank(), axis.line.x = element_blank(), axis.text.x=element_blank(), axis.ticks.x = element_blank())

```



```{r, echo=FALSE}

female_mouse_plot

male_mouse_plot

```

