---
title: "Results_setup"
author: "April Peterson"
date: "April 7, 2020"
output: html_document
---



```{r setup, echo=FALSE, include = FALSE}
library(knitr)
library(ggplot2)
#library(pwr)
library(plyr)
library(lattice)
library(dplyr)
library(raster)
library(lme4)
library(nlme)
library(RLRsim)
library(ggpubr)
library(reshape2)
#library(patchwork)

options(digits=2)

setwd("~.")#switch over to here()


load(file = "~./MLH1repo/data/MLH1/MLH1_data_setup_4.21.20.RData")
#load(file = "~./MLH1repo/data/MLH1/MLH1_data_setup_2.24.20.RData")
#load(file = "C:/Users/alpeterson7/Documents/MLH1repo/data/MLH1/MLH1_data_setup_1.31.20.RData")

#2.2.20
#load(file="C:/Users/April/Documents/MLH1repo/data/CleanBivData_1.27.20.RData")
#load(file="C:/Users/alpeterson7/Documents/MLH1repo/data/CleanBivData_1.27.20.RData")

load(file="~./MLH1repo/data/CleanBivData_6.3.20.RData")

load(file="~./MLH1repo/data/total_SC_30.12.19.RData")

#skeletonize
SC.skel = read.csv("~./MLH1repo/data/SCskel_output_feb20.csv", header = TRUE, strip.white = TRUE)

#load(file="~./MLH1repo/data/MLH1_data_setup_1.5.20.RData")

#setwd("~./MLH1repo/doc/")
#setwd("C:/Users/alpeterson7/Documents/MLH1repo/doc/")
#setwd("C:/Users/April/Documents/MLH1repo")
#load(file="data/MLH1/MLH1_data_setup.RData")

#load main data file
#load(file="C:/Users/April/Documents/MLH1repo/data/MLH1/MLH1_data_setup_1.5.20.RData")#added batch18
#load(file="C:/Users/April/Documents/MLH1repo/data/CleanBivData_1.28.20.RData")
#load(file="C:/Users/alpeterson7/Documents/MLH1repo/data/CleanBivData_1.28.20.RData")

#this MLH1 only goes up to batch16!
#load(file="C:/Users/alpeterson7/Documents/MLH1repo/data/MLH1/MLH1_data_setup_12.20.19.RData")#batch18
#load(file="C:/Users/alpeterson7/Documents/MLH1repo/data/MLH1/MLH1_data_setup_12.20.19.RData")#fixing bugs, formating
#load(file="data/MLH1/MLH1_data_setup_12.3.19.RData")#removed exclude mice
#load(file="data/MLH1/MLH1_data_setup_11.12.19.RData")#added batch17
#load(file="data/MLH1/MLH1_data_setup_11.11.19.RData")#deleted DUP image
#load(file="data/MLH1/MLH1_data_setup_9.26.19.RData")#added batch16
#load(file="data/MLH1/MLH1_data_setup_8.29.19.RData") #

#load(file="data/MetaData.RData") #this was replacing most updated data file

#load functions
source("~./MLH1repo/src/CommonFunc_MLH1repo.R")
```

<!-- Data Set Up Notes -->

```{r organizing.data, echo=FALSE }
#set the order of another column, based on another variable. consistant order for ploting

#Terminology Note, leptonema, zygonema, and pachynema diplonema diakinesis, are the stage names.
#-ene endings refer to the cells/units within the cell stage? (I think)

#apply this before ploting
MLH1_data <- MLH1_data %>%
  arrange(strain, sex, category, mouse) %>%
  mutate(Original.Name = factor(Original.Name)) #another category that you want the order to match
MLH1_data <- with(MLH1_data, MLH1_data[order(sex, strain),])

# sort your dataframe, by the focal categories
MLH1_data$mouse <- factor(MLH1_data$mouse, levels=unique(MLH1_data$mouse))
#use the above line for when order is out of wak

#MLH1_data <- with(MLH1_data, MLH1_data[order(category),])
AP_mouse_table.HQ$var <- as.numeric(AP_mouse_table.HQ$var)

AP_category_table <-  ddply(.data=AP_mouse_table.HQ,
                 .(strain,sex),
                 summarize,
                 sum.ncells = sum(Ncells),
                 mean.MLH1 = mean(mean_co),
                 var.MLH1 = var(mean_co),
                 AV.var_MLH1 = mean(var, na.rm=TRUE)
                                  
)

#there might be an error for changing wd
#write.table(AP_category_table, "~./MLH1repo/strain_table_variances.csv", sep=",", row.names = FALSE)

AP_mouse_table.HQ_target <- AP_mouse_table.HQ[!(is.na(AP_mouse_table.HQ$sex) | AP_mouse_table.HQ$sex==""), ]

remove_strains <- c("TOM","AST","CZECH","CAST","HMI","SPRET","CAROLI", "F1", "PERC")
AP_mouse_table.HQ_target <- AP_mouse_table.HQ_target[ ! AP_mouse_table.HQ_target$strain %in% remove_strains, ]

  
var.plot <- ggplot(AP_mouse_table.HQ_target, aes(y=var, x = sex, color=sex))+geom_jitter()+facet_wrap(~strain)+ggtitle("Plots of mouse Variances for MLH1 counts")+
  scale_color_manual(values=c("royalblue", "limegreen"))+theme_bw()

```

```{r misc.setup, echo=FALSE}

colors_of_strains <- c('WSB'= "#56B4E9",'G' ='cadetblue','LEW'= 'lightblue','PERC'= 'blue',
                       #blues
                       
                       'PWD'= 'red2',
                       'SKIVE'= 'coral1','KAZ'= 'coral4', 
                       
                       'TOM'= 'indianred1','AST' = 'tan2',
                       'CZECH'= 'brown1',
                       
                       'MSM'= 'deeppink', 'MOLF'= 'hotpink', #mol are pinks, bc they are fancy mice
                       
                    'CAST'='green','HMI'= 'forestgreen', #greens
                    
                    'SPRET'='gold','SPIC'= 'goldenrod1', #browns? color of mounds?
                    'CAROLI'='gold3',
                    
                    "F1"='grey', "other" = 'grey'
                    )

color_chrm_class <- c( '0' = "#00BFC4", '1' = "#7CAE00", '2' = "#F8766D", '3' = "#C77CFF", '4'= "#F564E3")
#4!!

#show_col(hue_pal()(5))

#add Rec group,

Curated_BivData$Rec.group <- ifelse(grepl("PWD male", Curated_BivData$category), 1, 
                              ifelse(grepl("MSM male", Curated_BivData$category), 1,
                                ifelse(grepl("SKIVE male", Curated_BivData$category), 1, 0)))

Curated_BivData$Rec.group_alt <- ifelse(grepl("PWD male", Curated_BivData$category), 1, 
                              ifelse(grepl("MSM male", Curated_BivData$category), 1, 0))


#apply this before ploting, to display strains in desired order
#MLH1_data <- MLH1_data %>%
#  arrange(strain, sex, category, mouse) %>%
#  mutate(Original.Name = factor(Original.Name)) #another category that you want the order to match
#MLH1_data <- with(MLH1_data, MLH1_data[order(sex, strain),])

# sort your dataframe, by the focal categories
#MLH1_data$mouse <- factor(MLH1_data$mouse, levels=unique(MLH1_data$mouse))


```


```{r Q1.rbar, echo=FALSE}

source("~./MLH1repo/src/CommonFunc_MLH1repo.R")

#read.csv of gamma estimates from above
gamma_estimates <- read.csv("~./MLH1repo/results/gamma_estimates.csv", header = TRUE)

table_gamma_estimates <- read.csv("~./MLH1repo/table.csv", header = TRUE)

#for(e in 1:length(cleanCurated_BivData$fileName)){
#  mini.IFD <- calq.intra.rbar(mini.IFD)
#  cleanCurated_BivData$rbar[e] <- new.calq.intra.rbar(cleanCurated_BivData[e,])
#  }

#calq the mouse / strain means for rbar

#summarize_rbar_table <- ddply(.data=cleanCurated_BivData,
#                 .(sex, strain),
#                 summarize,
#                 mean.rbar.all = mean(rbar, na.rm = TRUE),
                 
#                 mean.rbar.2CO = mean(rbar[which(hand.foci.count == 2)], na.rm = TRUE),
#                 mean.rbar.3CO = mean(rbar[which(hand.foci.count == 3)], na.rm = TRUE)
#)
#the 3 is negative...
#how best to merge rbar and gamma estiamtes (which estimate)

raw.gamma_estimates <-  gamma_estimates %>% filter(type.IFD == "raw.IFD") %>% filter( (class == "2CO") | (class == "3CO") )

table <- raw.gamma_estimates
#write.table(table, "~./MLH1repo/table.csv", sep=",",row.names = TRUE)

#write.table(summarize_rbar_table, "~./MLH1repo/RBAR.table.csv", sep=",",row.names = TRUE)

#what comparison of IFD and rbar would be logical
#plot rbar and gamma
ll <- ggplot(table_gamma_estimates, aes(y=mean.rbar, x = all.biv.gamma, color = class, shape = sex ))+geom_point()+facet_wrap(~strain)+ ggtitle("")+ylim(c(0,.5))

#mean rbars are up around 
#SKIVE male have extra (very strong interference)
#there's so much variance across the gamma estimates -- 
#most all females seem to have stronger interfernce
#there don't seem to be consistant patterns

#this plot shows much higher 2CO interference (via the gamma estimat from nrmIFD) in high rec males
#across other classes of bivalents 

#most all other estiamtes of gamma estimates are around 4
#

#house mouse raw nu is around 11

```


```{r MLH1.FEMALE.TABLE, echo=FALSE}
female_mouse.av <- subset(AP_mouse_table_w.Ages, select= -c(sex.y,sex.x,
                            subsp.y,subsp.x,
                    category.y,category.x, strain.x,
                    strain.y, mouse.1  )  )

female_mouse.av <- add_sex(female_mouse.av)
female_mouse.av <- add_strain(female_mouse.av)
female_mouse.av <- add_subsp(female_mouse.av)
female_mouse.av <- add_species(female_mouse.av)

female_mouse.avs_for.analysis <-  female_mouse.av %>% filter(sex== "female") %>% filter(species == "M.musculus") %>% filter(strain != "CZECH") %>% filter(strain != "CAST")

female_mouse.avs_for.analysis$subsp <- factor(female_mouse.avs_for.analysis$subsp, ordered = FALSE)
female_mouse.avs_for.analysis$sex <- factor(female_mouse.avs_for.analysis$sex, ordered = FALSE)
female_mouse.avs_for.analysis$strain <- factor(female_mouse.avs_for.analysis$strain, ordered = FALSE)
female_mouse.avs_for.analysis$species <- factor(female_mouse.avs_for.analysis$species, ordered = FALSE)

Musc.female_mouse.av <-  female_mouse.avs_for.analysis %>% filter(sex== "female") %>% filter(subsp == "Musc")

#Mol
#Mol.female_mouse.av <-  female_mouse.avs_for.analysis %>% filter(sex== "female") %>% filter(subsp == "Mol")

#Dom 
Dom.female_mouse.av <-  female_mouse.avs_for.analysis %>% filter(sex== "female") %>% filter(subsp == "Dom")

```

```{r MLH1.MALE.TABLE, echo=FALSE}
#AP_mouse_table.MLH1_HQ

#find the table that includes the las image data
male_MLH1mouse.av <- AP_mouse_table_w.Ages

male_MLH1mouse.av <- add_sex(male_MLH1mouse.av)
male_MLH1mouse.av <- add_strain(male_MLH1mouse.av)
male_MLH1mouse.av <- add_subsp(male_MLH1mouse.av)
male_MLH1mouse.av <- add_species(male_MLH1mouse.av)

fomo.male_mouse.av <-  male_MLH1mouse.av %>% filter(sex== "male") %>% filter(species == "M.musculus") 

fomo.male_mouse.av$subsp <- factor(fomo.male_mouse.av$subsp, ordered = FALSE)
fomo.male_mouse.av$sex <- factor(fomo.male_mouse.av$sex, ordered = FALSE)
fomo.male_mouse.av$strain <- factor(fomo.male_mouse.av$strain, ordered = FALSE)
fomo.male_mouse.av$species <- factor(fomo.male_mouse.av$species, ordered = FALSE)


Musc.male_mouse.av <-  fomo.male_mouse.av %>% filter(sex== "male") %>% filter(subsp == "Musc")
Mol.male_mouse.av <-  fomo.male_mouse.av %>% filter(sex== "male") %>% filter(subsp == "Mol")
#Dom version 
Dom.male_mouse.av <-  fomo.male_mouse.av %>% filter(sex== "male") %>% filter(subsp == "Dom")
```

```{r MLH1.MIXED.MODEL.setup, echo=FALSE, warning=FALSE, eval=TRUE}
#DF.HetC.MixedModel.HQ

#this blck is duplicated in setupData.rm

#https://rcompanion.org/handbook/G_03.html
#testing random effects within lme

#What are the main DFs for this code chunk
#AP_mouse_table_w.Ages   <- used to remove males which are too old (includes outgroups) 
#DF.HetC.MixedModel   <- only Mmusculus
#DF.HetC.MixedModel.HQ <- only mice of certain age, Q5 excluded

#variance is still chr
#AP_mouse_table_w.Ages$var <- as.numeric(AP_mouse_table_w.Ages$var)

#use the merged DF to filter by age 
#AP_mouse_table_w.Ages$strain <- AP_mouse_table_w.Ages$strain.x
#AP_mouse_table_w.Ages$sex <- AP_mouse_table_w.Ages$sex.x
#AP_mouse_table_w.Ages$subsp <- AP_mouse_table_w.Ages$subsp.x
#main file, make everything unordered factors
#AP_mouse_table_w.Ages <- add_species(AP_mouse_table_w.Ages)

DF.HetC.MixedModel <- AP_mouse_table_w.Ages[AP_mouse_table_w.Ages$species == "M.musculus",]

#remove the extra merged cols
#DF.HetC.MixedModel <- subset(DF.HetC.MixedModel, select= -c(sex.y,sex.x,
#                            subsp.y,subsp.x,
#                    category.y,category.x, strain.x,
#                    strain.y, mouse.1  )  )


#REMOVE EXTRA STRAINS
#DF.HetC.MixedModel <- DF.HetC.MixedModel[DF.HetC.MixedModel$subsp != "Cast",]
#remove musc strains
#DF.HetC.MixedModel <- DF.HetC.MixedModel[DF.HetC.MixedModel$strain != "AST",]
#DF.HetC.MixedModel <- DF.HetC.MixedModel[DF.HetC.MixedModel$strain != "TOM",]
#remove PERC, MOLF, CZECH, (no females)
#DF.HetC.MixedModel <- DF.HetC.MixedModel[DF.HetC.MixedModel$strain != "CZECH",]
#DF.HetC.MixedModel <- DF.HetC.MixedModel[DF.HetC.MixedModel$strain != "PERC",]

#DF.HetC.MixedModel <- droplevels(DF.HetC.MixedModel)#remove levels not used

#AP_mouse_table excluide Qual5 cells
DF.HetC.MixedModel.HQ <- AP_mouse_table.MLH1_HQ

DF.HetC.MixedModel.HQ <- add_species(DF.HetC.MixedModel.HQ)

#main df with variables coded as chr
DF.HetC.MixedModel.HQ$subsp <- factor(DF.HetC.MixedModel.HQ$subsp, ordered = FALSE)
DF.HetC.MixedModel.HQ$sex <- factor(DF.HetC.MixedModel.HQ$sex, ordered = FALSE)
DF.HetC.MixedModel.HQ$strain <- factor(DF.HetC.MixedModel.HQ$strain, ordered = FALSE)
#DF.HetC.MixedModel.HQ$species <- factor(DF.HetC.MixedModel.HQ$species, ordered = FALSE)

#kable(table(DF.HetC.MixedModel.HQ$sex, DF.HetC.MixedModel.HQ$strain))


all.cell.MM.HQ <- ddply(.data=DF.HetC.MixedModel.HQ,
                 .(sex, strain),
                 summarize,
                 all.cells = sum(Ncells)
)

```

```{r MLH1.HetC.rates, echo=FALSE, include=FALSE, warning=FALSE}
#calculate the initial HetC levels from best quality mice and cells (compare both levels (cell and mouse average levels))
#subset MLH1_DF, remove non passing mice (as diagnoised from plots)
#remove quality 5 cells

#outgroups
#SPIC
HetC.SPIC <- MLH1_data[(MLH1_data$strain == "SPIC")&(MLH1_data$quality < 5),]
#unique(HetC.SPIC$mouse)
#non-passing mice
SPIC.remove.mice <- c("30may18_SPIC_f1", "8jun18_SPIC_m2")
HetC.SPIC <- HetC.SPIC[ ! HetC.SPIC$mouse %in% SPIC.remove.mice, ]
#calq sex mean
SPIC.mean.MLH1.obs <- ddply(.data=HetC.SPIC, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
SPIC.HETC.val <- SPIC.mean.MLH1.obs$mean.MLH1[1] / SPIC.mean.MLH1.obs$mean.MLH1[2]

#SPRET
HetC.SPRET <- MLH1_data[(MLH1_data$strain == "SPRET")&(MLH1_data$quality < 5),]
#unique(HetC.SPRET$mouse)
#non-passing mice
#SPRET.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
SPRET.mean.MLH1.obs <- ddply(.data=HetC.SPRET, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

SPRET.HETC.val <- SPRET.mean.MLH1.obs$mean.MLH1[1] / SPRET.mean.MLH1.obs$mean.MLH1[2]

#CAROLI
HetC.CAROLI <- MLH1_data[(MLH1_data$strain == "CAROLI")&(MLH1_data$quality < 5),]
#unique(HetC.CAROLI$mouse)
#non-passing mice
#SPRET.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
CAROLI.mean.MLH1.obs <- ddply(.data=HetC.CAROLI, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

#cast
HetC.CAST <- MLH1_data[(MLH1_data$strain == "CAST")&(MLH1_data$quality < 5),]
#unique(HetC.CAST$mouse)
#non-passing mice
#X.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
CAST.mean.MLH1.obs <- ddply(.data=HetC.CAST, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
CAST.HETC.val <- CAST.mean.MLH1.obs$mean.MLH1[1] / CAST.mean.MLH1.obs$mean.MLH1[2]

#HMI
HetC.HMI <- MLH1_data[(MLH1_data$strain == "HMI")&(MLH1_data$quality < 5),]
#unique(HetC.HMI$mouse)
#non-passing mice
#X.remove.mice <- c("", "")
#HetC.SPRET <- HetC.SPRET[ ! HetC.SPRET$mouse %in% SPRET.remove.mice, ]
#calq sex mean
HMI.mean.MLH1.obs <- ddply(.data=HetC.HMI, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

#dom

#WSB
HetC.WSB <- MLH1_data[(MLH1_data$strain == "WSB")&(MLH1_data$quality < 5),]
#unique(HetC.WSB$mouse)
#non-passing mice
WSB.remove.mice <- c("8oct14_WSB_f1", "18nov17_WSB_f5", "16jun15_WSB_f3","10mar15_WSB_m2")
HetC.WSB <- HetC.WSB[ ! HetC.WSB$mouse %in% WSB.remove.mice, ]
#calq sex mean
WSB.mean.MLH1.obs <- ddply(.data=HetC.WSB, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

WSB.HETC.val <- WSB.mean.MLH1.obs$mean.MLH1[1] / WSB.mean.MLH1.obs$mean.MLH1[2]


#LEW
HetC.LEW <- MLH1_data[(MLH1_data$strain == "LEW")&(MLH1_data$quality < 5),]
unique(HetC.LEW$mouse)
#non-passing mice
LEW.remove.mice <- c("4jan17_LEW_f2")
HetC.LEW <- HetC.WSB[ ! HetC.LEW$mouse %in% LEW.remove.mice, ]

#calq sex mean
LEW.mean.MLH1.obs <- ddply(.data=HetC.LEW, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

LEW.HETC.val <- LEW.mean.MLH1.obs$mean.MLH1[1] / LEW.mean.MLH1.obs$mean.MLH1[2]


#G
HetC.G <- MLH1_data[(MLH1_data$strain == "G")&(MLH1_data$quality < 5),]
#unique(HetC.G$mouse)
#non-passing mice
G.remove.mice <- c("8jun15_G_f3","8jun15_G_f4")
HetC.G <- HetC.G[ ! HetC.G$mouse %in% G.remove.mice, ]

#calq sex mean
G.mean.MLH1.obs <- ddply(.data=HetC.G, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
G.HETC.val <- G.mean.MLH1.obs$mean.MLH1[1] / G.mean.MLH1.obs$mean.MLH1[2]


#PERC
HetC.PERC <- MLH1_data[(MLH1_data$strain == "PERC")&(MLH1_data$quality < 5),]
#unique(HetC.PERC$mouse)
#non-passing mice
#G.remove.mice <- c("8jun15_G_f3","8jun15_G_f4")
#HetC.G <- HetC.PERC[ ! HetC.PERC$mouse %in% PERC.remove.mice, ]

#calq sex mean
PERC.mean.MLH1.obs <- ddply(.data=HetC.PERC, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
G.HETC.val <- G.mean.MLH1.obs$mean.MLH1[1] / G.mean.MLH1.obs$mean.MLH1[2]

#MUSC

#PWD
HetC.PWD <- MLH1_data[(MLH1_data$strain == "PWD")&(MLH1_data$quality < 5),]
#unique(HetC.PWD$mouse)
#non-passing mice
PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
PWD.mean.MLH1.obs <- ddply(.data=HetC.PWD, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
PWD.HETC.val <- PWD.mean.MLH1.obs$mean.MLH1[1] / PWD.mean.MLH1.obs$mean.MLH1[2]

# CZECH
HetC.CZECH <- MLH1_data[(MLH1_data$strain == "CZECH")&(MLH1_data$quality < 5),]
#unique(HetC.CZECH$mouse)

#non-passing mice
#PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
#HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
CZECH.mean.MLH1.obs <- ddply(.data=HetC.CZECH, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

CZECH.HETC.val <- CZECH.mean.MLH1.obs$mean.MLH1[1] / CZECH.mean.MLH1.obs$mean.MLH1[2]


# SKIVE
HetC.SKIVE <- MLH1_data[(MLH1_data$strain == "SKIVE")&(MLH1_data$quality < 5),]
#unique(HetC.SKIVE$mouse)

#non-passing mice
#PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
#HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
SKIVE.mean.MLH1.obs <- ddply(.data=HetC.SKIVE, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

SKIVE.HETC.val <- SKIVE.mean.MLH1.obs$mean.MLH1[1] / SKIVE.mean.MLH1.obs$mean.MLH1[2]



# KAZ
HetC.KAZ <- MLH1_data[(MLH1_data$strain == "KAZ")&(MLH1_data$quality < 5),]
#unique(HetC.KAZ$mouse)

#non-passing mice
#PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
#HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
KAZ.mean.MLH1.obs <- ddply(.data=HetC.KAZ, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
KAZ.HETC.val <- KAZ.mean.MLH1.obs$mean.MLH1[1] / KAZ.mean.MLH1.obs$mean.MLH1[2]


#TOM
HetC.TOM <- MLH1_data[(MLH1_data$strain == "TOM")&(MLH1_data$quality < 5),]
#unique(HetC.TOM$mouse)

#non-passing mice
#PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
#HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
TOM.mean.MLH1.obs <- ddply(.data=HetC.TOM, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
TOM.HETC.val <- TOM.mean.MLH1.obs$mean.MLH1[1] / TOM.mean.MLH1.obs$mean.MLH1[2]



#AST
HetC.AST <- MLH1_data[(MLH1_data$strain == "AST")&(MLH1_data$quality < 5),]
#unique(HetC.AST$mouse)

#non-passing mice
#PWD.remove.mice <- c("1apr15_PWD_f2","8oct14_PWD_f2","8oct14_PWD_f5")
#HetC.PWD <- HetC.PWD[ ! HetC.PWD$mouse %in% PWD.remove.mice, ]

#calq sex mean
AST.mean.MLH1.obs <- ddply(.data=HetC.AST, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)
AST.HETC.val <- AST.mean.MLH1.obs$mean.MLH1[1] / AST.mean.MLH1.obs$mean.MLH1[2]


#Molosinus

#MSM
HetC.MSM <- MLH1_data[(MLH1_data$strain == "MSM")&(MLH1_data$quality < 5),]
unique(HetC.MSM$mouse)

#non-passing mice
MSM.remove.mice <- c("12sep16_MSM_f3")
HetC.MSM <- HetC.MSM[ ! HetC.MSM$mouse %in% MSM.remove.mice, ]

#calq sex mean
MSM.mean.MLH1.obs <- ddply(.data=HetC.MSM, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

MSM.HETC.val <- MSM.mean.MLH1.obs$mean.MLH1[1] / MSM.mean.MLH1.obs$mean.MLH1[2]


#MOLF
HetC.MOLF <- MLH1_data[(MLH1_data$strain == "MOLF")&(MLH1_data$quality < 5),]
unique(HetC.MOLF$mouse)

#non-passing mice
MOLF.remove.mice <- c("27oct18_MOLF_m3")
HetC.MOLF <- HetC.MOLF[ ! HetC.MOLF$mouse %in% MOLF.remove.mice, ]

#calq sex mean
MOLF.mean.MLH1.obs <- ddply(.data=HetC.MOLF, 
                 .(category),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                 mean.MLH1 = mean(adj_nMLH1.foci),
                 var.MLH1 = var(adj_nMLH1.foci)
)

MOLF.HETC.val <- MOLF.mean.MLH1.obs$mean.MLH1[1] / MOLF.mean.MLH1.obs$mean.MLH1[2]

```

```{r MLH1.HetC.plot, echo=FALSE, warning=FALSE}
#HETC plot
#change the main data? 

HetC_strain_table.M <- ddply(MLH1_data[(MLH1_data$quality < 5)&(MLH1_data$sex == "male"),], c("strain"), summarise,
                         Nmice = length(unique(mouse)),
                         Ncells  = length(adj_nMLH1.foci),
                         mean_co = format(round(  mean(adj_nMLH1.foci), 3 ), nsmall=3),
                         var = format(round(   var(nMLH1.foci),3), nsmall=3),
                         sd   = round(sd(adj_nMLH1.foci), 3),
                         se   = round(sd / sqrt(Ncells), 3),
                         cV = round( (as.numeric(sd) / as.numeric(mean_co) ),3)
)
#
#HetC_strain_table.M <- HetC_strain_table.M[ -c(7, 4, 10,11,12, 14, 17, 18,19), ]

HetC_strain_table.F <- ddply(MLH1_data[(MLH1_data$quality < 5)&(MLH1_data$sex == "female"),], c("strain"), summarise,
                         Nmice = length(unique(mouse)),
                         Ncells  = length(adj_nMLH1.foci),
                         mean_co = format(round(  mean(adj_nMLH1.foci), 3 ), nsmall=3),
                         var = format(round(   var(nMLH1.foci),3), nsmall=3),
                         sd   = round(sd(adj_nMLH1.foci), 3),
                         se   = round(sd / sqrt(Ncells), 3),
                         cV = round( (as.numeric(sd) / as.numeric(mean_co) ),3)
)
#HetC_strain_table.F <- HetC_strain_table.F[ -c(11), ]

#remove the 'other'

HetC_strain_table.M$sex <- "male"
HetC_strain_table.F$sex <- "female"

HetC_strain_table <- merge(HetC_strain_table.M, HetC_strain_table.F, by= "strain")

HetC_strain_table <- add_subsp(HetC_strain_table)

#HetC_strain_table$subsp <- c("Dom", "Dom", "Dom", "Musc", "Musc","Musc","Musc", "Cast", "Outgroup","Outgroup")

HetC_strain_table$mean_co.x <- as.numeric(HetC_strain_table$mean_co.x)
HetC_strain_table$mean_co.y <- as.numeric(HetC_strain_table$mean_co.y)
#str(HetC_strain_table)

Het.C.plot <- ggplot(data= HetC_strain_table, aes(x= mean_co.x, y=mean_co.y, color = subsp, label=strain ))+ geom_point(aes(size=2)) + xlim(c(20,35)) + ylim(c(20, 35)) + geom_abline(slope = 1, intercept = 0)+labs(x="male MLH1 mean",y="female MLH1 mean")+ggtitle("Heterochiasmy Plot")+
  scale_color_manual(values=c("royalblue", "limegreen",  "tomato", "slategray2", "plum", "grey")) + geom_text(data = HetC_strain_table, aes(label=HetC_strain_table$strain, x=mean_co.x, y= mean_co.y,  hjust = 0, nudge_x = 0.09, nudge_y = 0.09) )


```

```{r juvimice.list, echo=FALSE}
juvi_mice <- c(
  "30dec14_WSB_m2","30dec14_WSB_m4","30dec14_WSB_m1","30dec14_WSB_m3","30dec14_WSB_m5",
  "30sep14_G_m1","30sep14_G_m2","30sep14_G_m3","30sep14_G_m4","30sep14_G_m5",
  "12Feb17_LEW_m1","12Feb17_LEW_m2", "13sep17_LEW_m2", "13sep17_LEW_m1","13sep17_LEW_m3",
 
  "12sep17_PWD_m1","12sep17_PWD_m2","12sep17_PWD_m3",
   "30Dec16_MSM_m2","30Dec16_MSM_m3","30Dec16_MSM_m1"
  )

#REMOVE JUVI mice
#juvi.mouse_CurBiv_table <- mouse.avs_4MM[mouse.avs_4MM$mouse  %in% juvi_mice, ]  
#mouse.avs_4MM <- mouse.avs_4MM[! mouse.avs_4MM$mouse  %in% juvi_mice, ] 

```

```{r CurBiv.Mouse.av.TABLE, echo=FALSE}

#this block should be in the data set up
#the mouse averages will be used

#18jul19_31may19_SKIVE_m2_sp1_13.2_rev_8 is missing the 1CO position -- remove for now
cleanCurated_BivData <- cleanCurated_BivData %>% filter(fileName != "18jul19_31may19_SKIVE_m2_sp1_13.2_rev_8")

#cleanCurated_BivData
#removed the no hand foci count

mouse.avs_4MM <- ddply(cleanCurated_BivData, c("mouse"), summarise,
                        Nmice = length(unique(mouse)),
                        Ncells  = length(Obj.ID),
                       
                      # mean_CO = mean()
                       
                        mean_SC = as.numeric(format(round(  mean(chromosomeLength), 3 ), nsmall=3) ),
                        cV = cv(chromosomeLength),
                        var = as.numeric(format(round(   var(chromosomeLength),3), nsmall=3) ),
                        sd   = round(sd(chromosomeLength), 3),
                        se   = round(sd / sqrt(Ncells), 3),
                       
                       #calq mean.sc by chrm class
                       mean.SC_1CO = mean(chromosomeLength[which(hand.foci.count == 1)], na.rm = TRUE),
                       mean.SC_2CO = mean(chromosomeLength[which(hand.foci.count == 2)], na.rm = TRUE),
                       mean.SC_3CO = mean(chromosomeLength[which(hand.foci.count == 3)], na.rm = TRUE),
                       mean.SC_4CO = mean(chromosomeLength[which(hand.foci.count == 4)], na.rm = TRUE),
                       
                # IFD things
                #  mean_IFD_ABS = as.numeric(format(round(  mean(IFD1_ABS, na.rm = TRUE), 3 ), nsmall=3) ),
                # mean_IFD_PER = as.numeric(format(round(  mean(IFD1_PER, na.rm = TRUE), 3 ), nsmall=3) ),
                 
                 mean_IFD.2CO_ABS = mean(IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE),
                 mean_IFD.2CO_PER = mean(IFD1_PER[which(hand.foci.count == 2)], na.rm = TRUE),
                  
                       #CO position things, requires the melt?
              norm.first.foci.pos =  mean(PER_Foci_1[which(hand.foci.count == 1)]),
                  
              #sis.co.ten!!
              mean.siscoten = mean(SisCoTen, na.rm=TRUE),
              
              mean.siscoten_1CO = mean(SisCoTen[which(hand.foci.count == 1)], na.rm = TRUE),
              mean.siscoten_2CO = mean(SisCoTen[which(hand.foci.count == 2)], na.rm = TRUE),
              mean.siscoten_3CO = mean(SisCoTen[which(hand.foci.count == 3)], na.rm = TRUE),
              
              mean.telo.dist = mean(telo_dist, na.rm=TRUE),
              mean.cent.dist = mean(dis.cent, na.rm=TRUE)
)

#vari
mouse.avs_4MM <- add_sex(mouse.avs_4MM)
mouse.avs_4MM <- add_strain(mouse.avs_4MM)
mouse.avs_4MM <- add_subsp(mouse.avs_4MM)
mouse.avs_4MM <- add_category(mouse.avs_4MM)

#unordered for the mixed models (move this to the MM blocks...?)
#keep order for the plots?
mouse.avs_4MM$subsp <- factor(mouse.avs_4MM$subsp, ordered = FALSE)
mouse.avs_4MM$sex <- factor(mouse.avs_4MM$sex, ordered = FALSE)
mouse.avs_4MM$strain <- factor(mouse.avs_4MM$strain, ordered = FALSE)

#MAKE the same version of the TABLE but for the longest_biv_Dataset (when I get around to making it)
#code if males are high or low?

#REMOVE JUVI mice
juvi.mouse_CurBiv_table <- mouse.avs_4MM[mouse.avs_4MM$mouse  %in% juvi_mice, ]  
mouse.avs_4MM <- mouse.avs_4MM[! mouse.avs_4MM$mouse  %in% juvi_mice, ]  

#assign high and low
#divide musc males into groups
mouse.avs_4MM$Rec.group <- ifelse(grepl("PWD male", mouse.avs_4MM$category), 1, 
                                ifelse(grepl("MSM male", mouse.avs_4MM$category), 1,
                                 ifelse(grepl("SKIVE male", mouse.avs_4MM$category), 1, 0)))


mouse.avs_4MM$Rec.group.exclu <- ifelse(grepl("PWD male", mouse.avs_4MM$category), 1, 
                                ifelse(grepl("MSM male", mouse.avs_4MM$category), 1, 0))

```


```{r algorithm_performance_stats, echo=FALSE}

#sort by category, 
#compare total boxes and rate passed
#Curated_BivData  -- pass rate?

#number of mice, number of cells
#mean number of isolate bivs per cell,
#use these two metrics
#cell.level.BivData_table$boxs.IDd 
#cell.level.BivData_table$nboxes_passed

#calq the mean rate by category

cell.level.BivData_table$pass.rate <- cell.level.BivData_table$nboxes_passed / cell.level.BivData_table$boxs.IDd 

algorithm.stat.mouse <- ddply(cell.level.BivData_table, c("mouse"), summarise,
                        n_obs = length( unique(fileName) ),
                         mean_pass.rate = mean(pass.rate)
                         )

cell.level.BivData_table <- add_sex(cell.level.BivData_table)

algorithm.stat.category <- ddply(cell.level.BivData_table, c("sex", "strain"), summarise,
                        n_obs = length(unique(fileName)),
                        mean_pass.rate = mean(pass.rate)
                         )

#showing the table..
#data.frame(table( droplevels( Curated_BivData  %>%  filter(hand.foci.count  == 0 | hand.foci.count  == 1 |                                       hand.foci.count  == 2 | hand.foci.count  == 3 | hand.foci.count  == 4 ) )$category ) )
```


```{r Q1.biv.data_table.4MM.Male, echo=FALSE, eval=FALSE}

#add this to setup

#remove female, 
#add back in the BIVDATA from strains which were  removed for the sex-specific comparisons

#Curated_BivData_male

male.av_4MM <- ddply(cleanCurated_BivData, c("mouse"), summarise,
                        Nmice = length(unique(mouse)),
                        Ncells  = length(Obj.ID),
                       
                      # mean_CO = mean()
                       
                        mean_SC = as.numeric(format(round(  mean(chromosomeLength), 3 ), nsmall=3) ),
                        cV = cv(chromosomeLength),
                        var = as.numeric(format(round(   var(chromosomeLength),3), nsmall=3) ),
                        sd   = round(sd(chromosomeLength), 3),
                        se   = round(sd / sqrt(Ncells), 3),
                       
                       #calq mean.sc by chrm class
                       mean.SC_1CO = mean(chromosomeLength[which(hand.foci.count == 1)], na.rm = TRUE),
                       mean.SC_2CO = mean(chromosomeLength[which(hand.foci.count == 2)], na.rm = TRUE),
                       mean.SC_3CO = mean(chromosomeLength[which(hand.foci.count == 3)], na.rm = TRUE),
                       mean.SC_4CO = mean(chromosomeLength[which(hand.foci.count == 4)], na.rm = TRUE),
                       
                # IFD things
                #  mean_IFD_ABS = as.numeric(format(round(  mean(IFD1_ABS, na.rm = TRUE), 3 ), nsmall=3) ),
                # mean_IFD_PER = as.numeric(format(round(  mean(IFD1_PER, na.rm = TRUE), 3 ), nsmall=3) ),
                 
                 mean_IFD.2CO_ABS = mean(IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE),
                 mean_IFD.2CO_PER = mean(IFD1_PER[which(hand.foci.count == 2)], na.rm = TRUE),
                  
                       #CO position things, requires the melt?
              norm.first.foci.pos =  mean(PER_Foci_1[which(hand.foci.count == 1)]),
                  
              #sis.co.ten!!
              mean.siscoten = mean(SisCoTen, na.rm=TRUE),
              
              mean.siscoten_1CO = mean(SisCoTen[which(hand.foci.count == 1)], na.rm = TRUE),
              mean.siscoten_2CO = mean(SisCoTen[which(hand.foci.count == 2)], na.rm = TRUE),
              mean.siscoten_3CO = mean(SisCoTen[which(hand.foci.count == 3)], na.rm = TRUE),
              
              mean.telo.dist = mean(telo_dist, na.rm=TRUE),
              mean.cent.dist = mean(dis.cent, na.rm=TRUE)
)

#vari
male.av_4MM <- add_sex(male.av_4MM)
male.av_4MM <- add_strain(male.av_4MM)
male.av_4MM <- add_subsp(male.av_4MM)
male.av_4MM <- add_category(male.av_4MM)

#unordered for the mixed models (move this to the MM blocks...?)
#keep order for the plots?
male.av_4MM$subsp <- factor(male.av_4MM$subsp, ordered = FALSE)
male.av_4MM$sex <- factor(male.av_4MM$sex, ordered = FALSE)
male.av_4MM$strain <- factor(male.av_4MM$strain, ordered = FALSE)

#REMOVE JUVI mice
juvi.from.male.biv_table <- male.av_4MM[male.av_4MM$mouse  %in% juvi_mice, ]  
mouse.avs_4MM <- male.av_4MM[! male.av_4MM$mouse  %in% juvi_mice, ] 

```

```{r totSC_setup, echo=FALSE}
#SC.skel
#"anon.batch" "rand_name"  "bin_size"   "skel_size" , all batches included

SC.skel.OG <- SC.skel #5683

#MERGEING MLH1 with SKEL
MLH1.merge.Skel <- merge(original_DF, SC.skel, by.x = "Random.Name", by.y = "rand_name", all= F)

MLH1.merge.Skel <- add_mouse(MLH1.merge.Skel)
MLH1.merge.Skel <- add_strain(MLH1.merge.Skel)
MLH1.merge.Skel <- add_sex(MLH1.merge.Skel)
MLH1.merge.Skel <- add_subsp(MLH1.merge.Skel)
MLH1.merge.Skel <- add_category(MLH1.merge.Skel)
MLH1.merge.Skel <- add_subsp(MLH1.merge.Skel)
#5110, 

OG.MLH1.merge.Skel <- MLH1.merge.Skel #raw version of DF

#check for DUPs, #check for duplicatations of the random name
MLH1.merge.Skel$ fileName  <- as.character(MLH1.merge.Skel$fileName)
tot.SC.dupies <- MLH1.merge.Skel[duplicated(MLH1.merge.Skel$ fileName ),]

MLH1.merge.Skel <- MLH1.merge.Skel %>% filter( X == "") %>% filter(REDO.crop == "no")

MLH1.merge.Skel$bin_size <- as.numeric(MLH1.merge.Skel$bin_size)
MLH1.merge.Skel$skel_size <- as.numeric(MLH1.merge.Skel$skel_size)
#table(MLH1.merge.Skel$category)

#remove outliers
MLH1.merge.Skel <- MLH1.merge.Skel  %>% filter(bin_size < 60000)

```

```{r totSC.viz4outliers, echo=FALSE}

# -- EXAMINE the ggplot scatter plots for outliers
tot.sc <- ggplot(data= MLH1.merge.Skel, aes(y = bin_size, x=strain))+ geom_jitter()+facet_wrap(~category, scales = "free")

#round 1
SC.skel.outliers_round1 <- c(
  #MLH1.merge.Skel  %>% filter(category == "WSB male") %>% filter(skel_size > 2000)
  "10apr15_31mar15_WSB_m3_sp1_4_rev.tif",
  
  #MLH1.merge.Skel  %>% filter(category == "WSB female") %>% filter(skel_size > 2700)       
            "17nov16_3nov15_WSB_f1_sp3_4_rev.tif","1may16_3nov15_WSB_f1_sp2_6_rev.tif",
                      
    #MLH1.merge.Skel  %>% filter(category == "G male") %>% filter(skel_size > 20000) 
                      "19oct15_12oct15_G_m1_sp1_17.1_rev.tif",
  
  #MLH1.merge.Skel  %>% filter(category == "G female") %>% filter(skel_size > 20000) 
              "1mar16_20feb16_G_f3_sp1_8_rev.tif","21nov16_16jan16_G_f2_sp1_15_rev.tif",
  
  #MLH1.merge.Skel  %>% filter(category == "LEW male") %>% filter(skel_size < 1000)          
          "6mar18_1feb18_LEW_m1_sp1_21.5_rev",
  
  #MLH1.merge.Skel  %>% filter(category == "LEW female") %>% filter(skel_size > 20000)   
          "12jan17_4jan17_LEW_f1_sp1_32_rev.tif","20mar17_13jan17_LEW_f2_sp1_12_rev.tif","9apr18_1feb18_LEW_f1_sp1_23_rev.tif","9apr18_1feb18_LEW_f1_sp1_12_rev.tif", 
                      
       #MLH1.merge.Skel  %>% filter(category == "PWD male") %>% filter(skel_size > 20000)  
                      "6mar15_1mar15_PWD_m1_sp4_6.1_rev.tif","7mar15_1mar15_PWD_m1_sp4_2_rev.tif","20jul15_18may15_PWD_m2_sp1_10.2_rev.tif",
           
   #MLH1.merge.Skel  %>% filter(category == "PWD female") %>% filter(skel_size > 20000)
   "6may15_17apr15_PWD_f1_sp1_7_rev",  
       
      #MLH1.merge.Skel  %>% filter(category == "KAZ male") %>% filter(skel_size < 1000)
            "6aug19_10jul19_KAZ_m1_sp1_7.1_rev.tif",
            
    # MLH1.merge.Skel  %>% filter(category == "KAZ female") %>% filter(skel_size > 30000)     
    "16feb18_1feb18_KAZ_f4_sp1_20_rev.tif",  "8feb18_1feb18_KAZ_f1_sp1_24_rev.tif",  
  "16feb18_1feb18_KAZ_f4_sp1_1_rev.tif",   "8feb18_1feb18_KAZ_f1_sp1_5_rev.tif",   
 "16feb18_1feb18_KAZ_f4_sp1_17_rev.tif",  "1mar18_1feb18_KAZ_f3_sp1_8_rev.tif",   
 "7feb18_11jan18_KAZ_f3_sp1_27_rev.tif",  "20apr18_11jan18_KAZ_f1_sp1_6_rev.tif", 
 "16feb18_1feb18_KAZ_f2_sp1_5.2_rev.tif", "16feb18_1feb18_KAZ_f2_sp1_15_rev.tif", 
"7feb18_11jan18_KAZ_f3_sp1_13_rev.tif",  "13apr18_1feb18_KAZ_f6_sp1_25_rev.tif" ,
            
  # MLH1.merge.Skel  %>% filter(category == "SKIVE female") %>% filter(skel_size > 10000)
    "10jun19_31may19_SKIVE_f6_sp1_47_rev.tif","10jun19_31may19_SKIVE_f6_sp1_7_rev.tif",

# MLH1.merge.Skel  %>% filter(category == "MOLF male") %>% filter(skel_size < 1200)
"4jun19_28sep18_MOLF_m1_sp1_10.1_rev.tif",

#MLH1.merge.Skel  %>% filter(category == "AST male") %>% filter(skel_size > 2100)
"16aug19_27aug18_AST_m1_sp1_23_rev.tif",

#MLH1.merge.Skel  %>% filter(category == "MSM female") %>% filter(skel_size > 20000)
"21nov17_16nov17_MSM_f3_sp1_24_rev.tif","21nov17_16nov17_MSM_f3_sp1_3_rev.tif", "21nov17_16nov17_MSM_f3_sp1_27_rev.tif","4dec17_16nov17_MSM_f2_sp1_10_rev.tif",
"5aug17_14jul17_MSM_f1_sp1_25_rev.tif","24jan18_31dec17_MSM_f3_sp1_3_rev.tif", 
"24jan18_31dec17_MSM_f3_sp1_22_rev.tif","21nov17_16nov17_MSM_f3_sp1_17_rev.tif",

#tt <- MLH1.merge.Skel  %>% filter(category == "SPIC female") %>% filter(skel_size > 20000)
"27dec17_4dec17_SPIC_f1_sp1_12_rev.tif",  "5apr18_31dec17_SPIC_f2_sp1_1_rev.tif",
 "26sep18_30may18_SPIC_f4_sp1_14_rev.tif", "4feb18_31dec17_SPIC_f1_sp1_21_rev.tif", 
 "5apr18_31dec17_SPIC_f2_sp1_22_rev.tif",  "27dec17_4dec17_SPIC_f1_sp1_40_rev.tif", 
 "4jul18_30may18_SPIC_f1_sp1_6_rev.tif",   "26sep18_30may18_SPIC_f4_sp1_6_rev.tif", 
 "29dec17_4dec17_SPIC_f2_sp1_10_rev.tif",  "5sep17_21aug17_SPI_f2_sp1_37_rev.tif" , 
 "5sep17_21aug17_SPI_f2_sp1_15_rev.tif",   "26sep18_30may18_SPIC_f4_sp1_24_rev.tif",
"29dec17_4dec17_SPIC_f2_sp1_16_rev.tif",  "5sep17_21aug17_SPI_f2_sp1_30_rev.tif",  
"4feb18_31dec17_SPIC_f1_sp1_5_rev.tif",   "5apr18_31dec17_SPIC_f2_sp1_25_rev.tif", 
 "26sep18_30may18_SPIC_f4_sp1_4_rev.tif",  "5sep17_21aug17_SPI_f2_sp1_22_rev.tif",  
 "5sep17_21aug17_SPI_f2_sp1_19_rev.tif",   "5sep17_21aug17_SPI_f2_sp1_29_rev.tif",  
 "26sep18_30may18_SPIC_f4_sp1_3_rev.tif",  "5sep17_21aug17_SPI_f2_sp1_5.2_rev.tif", 
 "29dec17_4dec17_SPIC_f2_sp1_6_rev.tif",   "13oct17_21aug17_SPI_f1_sp1_13_rev.tif"  )


MLH1.merge.Skel_1 <- MLH1.merge.Skel[!MLH1.merge.Skel$fileName %in% SC.skel.outliers_round1, ]#62 removed


remove.mice_round2 <- c(
    #MLH1.merge.Skel  %>% filter(category == "G male") %>% filter(skel_size > 2500)
    "28jul15_22jun15_G_m2_sp1_5_rev.tif","12may15_30sep14_G_m5_sp1_26_rev.tif",  
    
    #MLH1.merge.Skel  %>% filter(category == "G female") %>% filter(skel_size > 20000)
  "19oct15_12oct15_G_m1_sp1_17.1_rev.tif",
  
#MLH1.merge.Skel_2  %>% filter(category == "PWD male") %>% filter(skel_size > 2100)
"20jul15_18may15_PWD_m1_sp1_10_rev.tif","22mar15_10mar15_PWD_m2_sp1_11.2_rev.tif","22mar15_10mar15_PWD_m1_sp1_4.1_rev.tif","20jul15_18may15_PWD_m1_sp1_7.2_rev.tif",  

#MLH1.merge.Skel_2  %>% filter(category == "PWD female") %>% filter(skel_size > 20000)
  "6may15_17apr15_PWD_f1_sp1_7_rev.tif",
  
  #MLH1.merge.Skel_2  %>% filter(category == "KAZ female") %>% filter(skel_size < 1000)
  "8feb18_1feb18_KAZ_f1_sp1_19_rev.tif",

#MLH1.merge.Skel_2  %>% filter(category == "LEW male") %>% filter(skel_size < 1000 | skel_size > 1750)
"6mar18_1feb18_LEW_m1_sp1_10_rev.tif","3mar15_13jan17_LEW_m1_sp1_15_rev.tif", "4feb17_4jan17_LEW_m1_sp1_13_rev.tif","6mar18_1feb18_LEW_m1_sp1_21.5_rev.tif",

#MLH1.merge.Skel_2  %>% filter(category == "LEW female") %>% filter(skel_size > 2750 ) 
"20mar17_13jan17_LEW_f2_sp1_10_rev.tif",

# MLH1.merge.Skel_2  %>% filter(category == "CAROLI male") %>% filter(skel_size < 1400 )
"31aug18_1mar18_CAROLI_m1_sp3_29.2_rev.tif",

#MLH1.merge.Skel_2  %>% filter(category == "MSM male") %>% filter(skel_size < 1200 )
"16aug17_5jul17_MSM_m1_sp1_6.1_rev.tif",

#tt <- MLH1.merge.Skel_2  %>% filter(category == "MSM female") %>% filter(skel_size > 2850 ) 
"29nov17_16nov17_MSM_f1_sp1_10_rev.tif", "4dec17_16nov17_MSM_f2_sp1_24_rev.tif", "21nov17_16nov17_MSM_f3_sp1_26_rev.tif",
#SPIC male  x
#SPIC female  x
#TOM x
#AST x
#CZECH male x 

#MLH1.merge.Skel_2  %>% filter(category == "SPRET male") %>% filter(skel_size < 1900 ) 
 "24may17_8may17_SPRET_m1_sp1_21.1_rev.tif",
#SPRET female X
#MLH1.merge.Skel_2  %>% filter(category == "HMI male") %>% filter(skel_size < 1000 ) 
"29dec17_4dec17_HMI_m1_sp1_4.1_rev.tif"
)
#3remove.mice_round2

MLH1.merge.Skel_2 <- MLH1.merge.Skel_1[!MLH1.merge.Skel_1$fileName %in% remove.mice_round2, ]
#MLH1.merge.Skel <- MLH1.merge.Skel[! (MLH1.merge.Skel$fileName %in% SC.skel.outliers_round1),]
#MLH1.merge.Skel <- MLH1.merge.Skel[! (MLH1.merge.Skel$fileName %in% remove.mice_round2),]
all.remove <- paste( c(SC.skel.outliers_round1, remove.mice_round2 ) )

MLH1.merge.Skel <- MLH1.merge.Skel_2

MLH1.merge.Skel <- add_species(MLH1.merge.Skel)

```

```{r tot.skel.table, echo=FALSE}
totSC.mouse.av.table <- ddply(.data=MLH1.merge.Skel, 
                 .(mouse),
                 summarize, 
                 ncells = length(unique(Original.Name)),
                 nmice = length(unique(mouse)),
                # mean.MLH1 = mean(adj_nMLH1.foci, na.rm = TRUE),
                # var.MLH1 = var(adj_nMLH1.foci, na.rm = TRUE),
                 
                 mean.skel = mean(skel_size, na.rm = TRUE),
                #se for skel
                
                 mean.bin =  mean(bin_size, na.rm = TRUE)
                 
)

totSC.mouse.av.table <- add_strain(totSC.mouse.av.table)
totSC.mouse.av.table <- add_sex(totSC.mouse.av.table)
totSC.mouse.av.table <- add_category(totSC.mouse.av.table)
totSC.mouse.av.table <- add_subsp(totSC.mouse.av.table)
totSC.mouse.av.table <- add_species(totSC.mouse.av.table)

#unorder the factors
totSC.mouse.av.table$subsp <- factor(totSC.mouse.av.table$subsp, ordered = FALSE)
totSC.mouse.av.table$sex <- factor(totSC.mouse.av.table$sex, ordered = FALSE)
totSC.mouse.av.table$strain <- factor(totSC.mouse.av.table$strain, ordered = FALSE)
totSC.mouse.av.table$species <- factor(totSC.mouse.av.table$species, ordered = FALSE)

#add rec group
totSC.mouse.av.table$Rec.group <- ifelse(grepl("PWD male", totSC.mouse.av.table$category), 1, 
                              ifelse(grepl("MSM male", totSC.mouse.av.table$category), 1,
                                ifelse(grepl("SKIVE male", totSC.mouse.av.table$category), 1, 0)))

OG.totSC.mouse.av.table <- totSC.mouse.av.table

#REMOVE JUVI mice
tot.SC_juvi.male <- totSC.mouse.av.table[totSC.mouse.av.table$mouse  %in% juvi_mice, ]

totSC.mouse.av.table <- totSC.mouse.av.table[! totSC.mouse.av.table$mouse  %in% juvi_mice, ] 

totSC.mouse.av.table <- totSC.mouse.av.table %>% filter(strain!="CAST" & strain !="F1" & strain !="SPIC" & strain !=  "CAROLI" & strain !="SPRET"& strain !="HMI"& strain !="PERC")

mouse.av_sc_female <- ggplot(data= OG.totSC.mouse.av.table[OG.totSC.mouse.av.table$sex == "female",], aes(y = mean.skel, x=mouse, color=strain))+ geom_point()+scale_color_manual(values=colors_of_strains)+
  facet_wrap(Rec.group~subsp, scales="free")+ theme(axis.title.x=element_blank(),        axis.text.x=element_blank(), axis.ticks.x=element_blank()) + ylim(c(1500,3000 ))+ggtitle("Female Mouse av. total SC area")

mouse.av_sc_male <- ggplot(data= OG.totSC.mouse.av.table[OG.totSC.mouse.av.table$sex == "male",], aes(y = mean.skel, x=mouse, color=strain))+ geom_point()+scale_color_manual(values=colors_of_strains)+
  facet_wrap(Rec.group~subsp, scales="free")+ theme(axis.title.x=element_blank(),        axis.text.x=element_blank(), axis.ticks.x=element_blank()) + ylim(c(1200,1850 ))+ggtitle("Mouse av. total SC area")

```

```{r tot.SC.setup, echo = FALSE}

totSC.strain.av.table <- ddply(.data=totSC.mouse.av.table, 
                 .(sex,strain),
                 summarize, 
                 ncells = sum(ncells),
                 nmice = length(unique(mouse)),
                # mean.MLH1 = mean(adj_nMLH1.foci, na.rm = TRUE),
                # var.MLH1 = var(adj_nMLH1.foci, na.rm = TRUE),
                 
                 mean.skel = mean(mean.skel, na.rm = TRUE),
                 mean.bin =  mean(mean.bin, na.rm = TRUE)
                 
)

totSC.strain.av.table <- add_subsp(totSC.strain.av.table)

```

```{r LONG.SHORT.biv_setup, echo=FALSE}

#FROM q1
#Q1.long.biv_1CO <-  real.long.bivData %>% filter(species =="M.musculus") %>% filter(hand.foci.count == 1) %>% filter(strain != "MOLF") %>% filter(strain != "CZECH")
#Q1.short.biv_1CO <-  real.short.bivData %>% filter(species =="M.musculus") %>% filter(hand.foci.count == 1)%>% filter(strain != "MOLF") %>% filter(strain != "CZECH")
#from Q2 IFD
#male.long.biv.2CO_IFD <- real.long.bivData %>% filter(sex== "male") %>% filter(species =="M.musculus") %>% filter(hand.foci.count == 2)
##long biv
#male.long.biv <- real.long.bivData %>% filter(sex== "male") %>% filter(species == "M.musculus") 
#table( droplevels( male.long.biv$strain)  )

#FROM q1 
REAL.short_mouse_table <- ddply(real.short.bivData, c("mouse"), summarise,
                        n_obs = length(Obj.ID),
                        ncells = length(unique(fileName)),
                         mean_SC = mean(chromosomeLength),
                        
                      mean.SC_1CO = mean(chromosomeLength[which(hand.foci.count == 1)], na.rm = TRUE),
                       mean.SC_2CO = mean(chromosomeLength[which(hand.foci.count == 2)], na.rm = TRUE),
                       mean.SC_3CO = mean(chromosomeLength[which(hand.foci.count == 3)], na.rm = TRUE),
                       mean.SC_4CO = mean(chromosomeLength[which(hand.foci.count == 4)], na.rm = TRUE),
                        
                      #make sure 1CO  
                       #IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE
                    mean_F1pos_ABS =  mean(Foci1[which(hand.foci.count == 1)]),
                    mean_F1pos_PER =  mean(PER_Foci_1[which(hand.foci.count == 1)]),
                           
                      meanIFD2CO_raw = mean(IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE),
                     meanIFD2CO_norm = mean(IFD1_PER[which(hand.foci.count == 2)], na.rm = TRUE)
                                            
                         )

REAL.short_mouse_table <- add_sex(REAL.short_mouse_table)
REAL.short_mouse_table <- add_strain(REAL.short_mouse_table)
REAL.short_mouse_table <- add_subsp(REAL.short_mouse_table)
REAL.short_mouse_table <- add_category(REAL.short_mouse_table)

REAL.short_mouse_table$sex <- factor(REAL.short_mouse_table$sex, ordered = FALSE)
REAL.short_mouse_table$strain <- factor(REAL.short_mouse_table$strain, ordered = FALSE)
REAL.short_mouse_table$subsp <- factor(REAL.short_mouse_table$subsp, ordered = FALSE)

#divide musc males into groups
REAL.short_mouse_table$Rec.group <- ifelse(grepl("PWD male", REAL.short_mouse_table$category), 1, 
                                  ifelse(grepl("MSM male", REAL.short_mouse_table$category), 1,
                                  ifelse(grepl("SKIVE male", REAL.short_mouse_table$category), 1,
                                           0)))

REAL.short_mouse_table$Rec.group.exclu <- ifelse(grepl("PWD male", REAL.short_mouse_table$category), 1, 
                                ifelse(grepl("MSM male", REAL.short_mouse_table$category), 1, 0))

###LONG BIV

REAL.long_mouse_table <- ddply(real.long.bivData, c("mouse"), summarise,
                       n_obs = length(Obj.ID),
                        ncells = length(unique(fileName)),
                         mean_SC = mean(chromosomeLength),
                        
                      mean.SC_1CO = mean(chromosomeLength[which(hand.foci.count == 1)], na.rm = TRUE),
                       mean.SC_2CO = mean(chromosomeLength[which(hand.foci.count == 2)], na.rm = TRUE),
                       mean.SC_3CO = mean(chromosomeLength[which(hand.foci.count == 3)], na.rm = TRUE),
                       mean.SC_4CO = mean(chromosomeLength[which(hand.foci.count == 4)], na.rm = TRUE),
                        
                      #make sure 1CO,  #IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE
                    mean_F1pos_ABS =  mean(Foci1[which(hand.foci.count == 1)]),
                    mean_F1pos_PER =  mean(PER_Foci_1[which(hand.foci.count == 1)]),
                           
                      meanIFD2CO_raw = mean(IFD1_ABS[which(hand.foci.count == 2)], na.rm = TRUE),
                     meanIFD2CO_norm = mean(IFD1_PER[which(hand.foci.count == 2)], na.rm = TRUE)
                         )

REAL.long_mouse_table <- add_sex(REAL.long_mouse_table)
REAL.long_mouse_table <- add_strain(REAL.long_mouse_table)
REAL.long_mouse_table <- add_subsp(REAL.long_mouse_table)
REAL.long_mouse_table <- add_category(REAL.long_mouse_table)

REAL.long_mouse_table$sex <- factor(REAL.long_mouse_table$sex, ordered = FALSE)
REAL.long_mouse_table$strain <- factor(REAL.long_mouse_table$strain, ordered = FALSE)
REAL.long_mouse_table$subsp <- factor(REAL.long_mouse_table$subsp, ordered = FALSE)

#divide musc males into groups
REAL.long_mouse_table$Rec.group <- ifelse(grepl("PWD male", REAL.long_mouse_table$category), 1, 
                                  ifelse(grepl("MSM male", REAL.long_mouse_table$category), 1,
                                  ifelse(grepl("SKIVE male", REAL.long_mouse_table$category), 1,
                                           0)))

REAL.long_mouse_table$Rec.group.exclu <- ifelse(grepl("PWD male", REAL.long_mouse_table$category), 1, 
                                ifelse(grepl("MSM male", REAL.long_mouse_table$category), 1, 0))


#find which one 
```


# Datasubsets


```{r Q1.Short.Long_biv.setup, echo=FALSE}

#REAL.long_mouse_table
#REAL.short_mouse_table

#make the Q1 strain list
Q1.real.short_mouse_table <- REAL.short_mouse_table %>% filter( (strain != "CZECH") & (strain != "MOLF") )

Q1.real.long_mouse_table <- REAL.long_mouse_table %>% filter( (strain != "CZECH") & (strain != "MOLF") )

```


# MLH1 models

M1 - subsp, sex, (1 | strain)
M2 - subsp, sex, strain
M3 - sex, strain
M4 - strain (sex specific)


#MLH1 variance models

M1 - subsp, sex, (1 | strain)
M2 - subsp, sex, strain
M3 - sex, strain
M4 - strain (sex specific)


```{r M1.MLH1.var_cv, echo=FALSE, warning=FALSE, message=FALSE}
MLH1var_M1 <- lmer( var ~ subsp * sex +(1|strain), data=DF.HetC.MixedModel.HQ )
MLH1var_M1.reduce.sex <- lmer( var ~ subsp  +(1|strain), data=DF.HetC.MixedModel.HQ )
MLH1var_M1.reduce.subp <- lmer( var ~ sex  +(1|strain), data=DF.HetC.MixedModel.HQ )

#summary(MLH1var_M1)
LmerMLH1_VAR_int <- drop1(MLH1var_M1, test="Chisq")$`Pr(Chi)`[2]
LmerMLH1_VAR_sex <- anova(MLH1var_M1, MLH1var_M1.reduce.sex)$`Pr(>Chisq)`[2]
LmerMLH1_VAR_subsp <- anova(MLH1var_M1, MLH1var_M1.reduce.subp)$`Pr(>Chisq)`[2]
LmerMLH1_VAR_strain <- exactRLRT(MLH1var_M1)$p.value

LmerMLH1_VAR_results <- data.frame(sub.sp = LmerMLH1_VAR_subsp,
sex.results =  LmerMLH1_VAR_sex, interaction.pval = LmerMLH1_VAR_int,  rand.pval = LmerMLH1_VAR_strain)

```

```{r M2.MLH1.var, echo=FALSE, include=FALSE}
#not including this model for now / brivity
#$$mouse CO metric  ~=~ subsp * sex * strain + \varepsilon$$

MLH1var_M2 <- lm( var ~ subsp * sex * strain,  data=DF.HetC.MixedModel.HQ )
MLH1var_M2_sum <- summary(MLH1var_M2)

#summary(MLH1var_M2)
#anova(MLH1var_M2)  
#as.data.frame( round(summary(MLH1var_M2)$coefficients, 6)) #table of p values for coefficients.

MLH1cv_M2 <- lm(cV ~ subsp*sex*strain, data=DF.HetC.MixedModel.HQ)

#summary(MLH1cv_M3)
#anova(MLH1cv_M2)
#as.data.frame( round(summary(MLH1cv_M2)$coefficients, 6))

#Q12 var
MLH1var_M2_Q12 <- lm( var ~ subsp*sex*strain,  data=Q12_mouse_table_w.Ages )

#summary(MLH1var_M3_Q12)
#anova(MLH1var_M2_Q12)  
#as.data.frame( round(summary(MLH1var_M2_Q12)$coefficients, 6))

#Q12 cv
MLH1cv_M2_Q12 <- lm( cV ~ subsp*sex*strain, data=Q12_mouse_table_w.Ages )

#summary(MLH1cv_M2_Q12)
#anova(MLH1cv_M2_Q12)#sex large F
#as.data.frame( round(summary(MLH1cv_M2_Q12)$coefficients, 6))
```

```{r M3.MLH1.var, echo=FALSE}

glmMLH1Var_M3 <- glm( var ~ sex * strain,  data=DF.HetC.MixedModel.HQ )
glmMLH1Var_M3_sum <- summary(glmMLH1Var_M3)
#round(glmMLH1Var_M3_sum$coefficients[,c(1,4)], 5)

MLH1cv_M3 <- glm(cV ~ sex * strain, data=DF.HetC.MixedModel.HQ)
#summary(MLH1cv_M4)
#round(summary(MLH1cv_M3)$coefficients[,c(1,4)], 6)

### Q12 var
MLH1var_M3_Q12 <- glm( var ~ sex*strain, data=Q12_mouse_table_w.Ages )
MLH1var_M3_Q12_sum <- summary(MLH1var_M3_Q12)

#as.data.frame( round(summary(MLH1var_M3_Q12)$coefficients[,c(1,4)], 6))
#round(summary(MLH1var_M3_Q12)$coefficients[,c(1,4)], 6)

#Q12 cv
MLH1cv_M4_Q12 <- glm( cV ~ sex*strain, data=Q12_mouse_table_w.Ages )
#round(summary(MLH1cv_M4_Q12)$coefficients[,c(1,4)], 6)
```

```{r MLH1.var.M4}

#male

#female
```


# DMC1 Results

main table (DMC1.mean.table), t.tests  , ratios

set up, t.tests, correlations

```{r DMC1.setup, echo=FALSE}
#load DMC1 csv
#DMC1.DF <- read.csv("~./DMC1/newJuviQuant.csv", header = TRUE)
DMC1.DF <- read.csv("~./MLH1repo/data/DMC1newJuviQuant.csv", header = TRUE)


DMC1.DF$fileName <- DMC1.DF$Original.Name
DMC1.DF <- add_mouse(DMC1.DF)
DMC1.DF <- add_strain(DMC1.DF)
DMC1.DF <- add_category(DMC1.DF)
DMC1.DF <- add_subsp(DMC1.DF)
DMC1.DF <- DMC1.DF[DMC1.DF$stage != "P",]

#make DMC1 table
DMC1.mean.obs.L <- ddply(.data=DMC1.DF[DMC1.DF$stage == "L",],
                 .(category),
                 summarize, 
                 
                 ncells = length(fileName),
                 mean.count = mean( total.count)
)
DMC1.mean.obs.L$stage <- "L"

DMC1.mean.obs.Z <- ddply(.data=DMC1.DF[DMC1.DF$stage == "Z",],
                 .(category),
                 summarize, 
                 ncells = length(fileName),
                 mean.count = mean( total.count)
)
DMC1.mean.obs.Z$stage <- "Z"

DMC1.mean.table <- rbind(DMC1.mean.obs.L,DMC1.mean.obs.Z)

#write.table(DMC1.mean.table, "~./MLH1repo/DMC1.mean.table.csv", sep=",",
#            row.names = FALSE)

DMC1.DF$rec_group <- ifelse(grepl("WSB", DMC1.DF$strain), "Low",
                          ifelse(grepl("G",DMC1.DF$strain), "Low",
                                 
              ifelse(grepl("KAZ", DMC1.DF$strain), "Low",
            ifelse(grepl("PWD", DMC1.DF$strain), "High",
               ifelse(grepl("MSM", DMC1.DF$strain), "High","")))))

#make category averages from AP_mouse_table.HQ
mean.MLH1.obs <- ddply(.data=AP_mouse_table.HQ,
                 .(category),
                 summarize, 
                 mean.MLH1 = mean(mean_co),
                 var.MLH1 = var(mean_co)
)

DMC1.target.strains <- subset(mean.MLH1.obs, category == "G male" |
                   category == "WSB male" |
                     category == "KAZ male" |
                  category == "MSM male" |
                    category == "PWD male")
#attach this mini DF to the DMC1 data


```


```{r DMC1_t.tests, echo=FALSE, warning=FALSE}
#2. t-tests for the DMC1 counts 
#need to account for sample sizes when comparing t.tests (KAZ and G don't have equal across )
#best case scnario -- more microscoping to get ~20 cells for each stage by strain combo


#high vs low group (L)
ttest.HighLow.L.pval <- t.test(DMC1.DF$total.count[( (DMC1.DF$stage == "L") & ( ( DMC1.DF$strain == "MSM") | (DMC1.DF$strain == "PWD") ) )  ],
               DMC1.DF$total.count[( (DMC1.DF$stage == "L") & ( ( DMC1.DF$strain == "WSB") | (DMC1.DF$strain == "G") | (DMC1.DF$strain == "KAZ") ) )]    )$p.value
# p-value =  0.002145


#high vs low group (Z)
ttest.HighLow.Z.pval <- t.test(DMC1.DF$total.count[( (DMC1.DF$stage == "Z") & ( ( DMC1.DF$strain == "MSM") | (DMC1.DF$strain == "PWD") ) )  ],
               DMC1.DF$total.count[( (DMC1.DF$stage == "Z") & ( ( DMC1.DF$strain == "WSB") | (DMC1.DF$strain == "G") | (DMC1.DF$strain == "KAZ") ) )]    )$p.value
# p-value = 0.6628


#dom vs musc (L) (2 subsp vs)
ttest.subsp.L <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "L")], DMC1.DF$total.count[(DMC1.DF$subsp == "Musc") & (DMC1.DF$stage == "L")] )
# p-value = 0.003016

#dom vs musc (Z)
ttest.subsp.Z <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "Z")], DMC1.DF$total.count[(DMC1.DF$subsp == "Musc") & (DMC1.DF$stage == "Z")] )
#p-value = 0.09588

#KAZ vs Dom (Z) (only 1 L cell)
ttest.KAZ.Dom.z <- t.test(DMC1.DF$total.count[(DMC1.DF$subsp == "Dom") & (DMC1.DF$stage == "Z")], 
      DMC1.DF$total.count[(DMC1.DF$strain == "KAZ") & (DMC1.DF$stage == "Z")] )

#p-value = 0.004148
#Kaz Z are higher than Dom
```


```{r DMC1.rand.calq, echo=FALSE}

DMC1.mean.obs.L$mean.count.L <- DMC1.mean.obs.L$mean.count
DMC1.mean.obs.Z$mean.count.Z <- DMC1.mean.obs.Z$mean.count


DMC1table <- merge(DMC1.mean.obs.L, DMC1.mean.obs.Z, by="category")

DMC1table.main <- merge(DMC1.target.strains, DMC1table, by="category")

MLH1.DMC1.L_cor <- cor(DMC1table.main$mean.MLH1, DMC1table.main$mean.count.L, method = c("pearson"))#MLH1.DMC1.Z_cor

MLH1.DMC1.Z_cor <- cor(DMC1table.main$mean.MLH1, DMC1table.main$mean.count.Z, method = c("pearson"))#0.2793237
```


```{r DMC1.ratios, echo=FALSE}

##RATIOS
DMC1table.main$MLH1.L_ratio <- DMC1table.main$mean.MLH1/ DMC1table.main$mean.count.L 
DMC1table.main$MLH1.Z_ratio <- DMC1table.main$mean.MLH1 / DMC1table.main$mean.count.Z
  
#colnames(DMC1table.main) <- c("category", "mean.MLH1", "", "", "")

#DMC1.mean.table
DMC1.mean.table.99 <- subset(DMC1table.main, select= -c(var.MLH1,  mean.count.x,  mean.count.y, stage.x, stage.y))

colnames(DMC1.mean.table.99) <- c("category","mean.MLH1","ncells.L","mean.L",
                  "ncells.Z", "mean.Z", "MLH1.L_ratio", "MLH1.Z_ratio")


WSB_DMC1.Z_CO_ratio <-   ( DMC1table.main %>% filter(category == "WSB male") )$mean.count.L / (DMC1table.main %>% filter(category == "WSB male"))$mean.MLH1
  
G_DMC1.Z_CO_ratio <-   ( DMC1table.main %>% filter(category == "G male") )$mean.count.L / (DMC1table.main %>% filter(category == "G male"))$mean.MLH1

MSM_DMC1.Z_CO_ratio <- ( DMC1table.main %>% filter(category == "MSM male") )$mean.count.L / (DMC1table.main %>% filter(category == "MSM male"))$mean.MLH1

PWD_DMC1.Z_CO_ratio <-( DMC1table.main %>% filter(category == "PWD male") )$mean.count.L / (DMC1table.main %>% filter(category == "PWD male"))$mean.MLH1



DMC1table.main$category <- factor(DMC1table.main$category, levels = c("WSB male","G male","KAZ male",               "PWD male","MSM male"), ordered = TRUE )

DMC1table.main <- DMC1table.main[order(DMC1table.main$category),]

kable(head(DMC1table.main),  caption = "Table X. DMC1 foci counts per cell summary")


DMC1.Lratio_t.test <- t.test(  (DMC1table.main %>% filter(  ( category == "G male" | category == "WSB male" | category == "KAZ male" ) ) )$MLH1.L_ratio, 
                (DMC1table.main %>% filter(  ( category == "PWD male" | category == "MSM male") ) )$MLH1.L_ratio        )
                               

DMC1.Zratio_t.test <- t.test(  (DMC1table.main %>% filter(  ( category == "G male" | category == "WSB male" | category == "KAZ male" ) ) )$MLH1.Z_ratio, 
                (DMC1table.main %>% filter(  ( category == "PWD male" | category == "MSM male") ) )$MLH1.Z_ratio        )

```





# SAVE the data

```{r Save.File, echo=FALSE}
#save Rdata
save.image("~./MLH1repo/data/Results_setup_4.17.20.RData")
#save.image("data/BivData_4_PCA.RData")
```

